calimero-network/core

crates/server/src/admin/handlers/fetch_did.rs
=> feat(admin-api): update get did return type

Cargo.lock, crates/node-primitives/src/lib.rs, crates/node/src/cli/init.rs, crates/node/src/lib.rs, crates/node/src/runtime_compat.rs, crates/node/src/types.rs, crates/primitives/Cargo.toml, crates/primitives/src/context.rs, crates/primitives/src/events.rs, crates/primitives/src/hash.rs, crates/primitives/src/identity.rs, crates/primitives/src/transaction.rs
Updates to base primitives used across the workspace
=> chore(store-revamp): bump node

README.mdx
Finally found a graphical tool for this - https://mermaidchart.com
```mermaid
flowchart TD
subgraph DatastoreImpl["Implementations"]
rdb["RocksDB"]
mem["Memory"]
lvl["LevelDB"]
s3["S3"]
end
subgraph ctx["Context"]
direction LR
me["Metadata"]
st["State"]
id["Identities"]
tx["Transactions"]
end
subgraph kad["Kademlia"]
pe["Peers"]
end
subgraph net["Network"]
direction LR
kad
end
subgraph gen["Generic"]
direction LR
sc["Scope"]
fr["Fragment"]
end
subgraph DatastoreWrapper["Content"]
ctx
net
gen
end
subgraph Datastore["Data Store"]
DatastoreWrapper
DatastoreImpl
end
subgraph BlobstoreImpl["Implementations"]
direction LR
fs["File System"]
blobS3["S3"]
end
subgraph BlobstoreWrapper["Content"]
direction LR
apps["Applications"]
genData["Generic Data"]
end
subgraph Blobstore["Blob Store"] …
```
=> docs: update architecture diagram

crates/meroctl/src/cli/context/list.rs
Everything stays the same, had to add few structures because of the api response.
=> Cli context list fix

crates/node/src/lib.rs
=> fix(node): remove necessity of application installation for peers query

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/improvement.md, .github/pull_request_template.md, .husky/pre-commit, .prettierignore, CODE_OF_CONDUCT.md, CONTRIBUTING.md, CONTRIBUTORS.md, LICENSE.md, README.mdx, crates/identity/README.md, crates/sdk/design-guide.md, crates/sdk/macros/design-guide.md, package.json, pnpm-lock.yaml, prettier.config.cjs
Add prettier to format md/mdx files and husky for pre-commit hooks in root. 
Try it manually from the root:
`pnpm format:md`
=> chore: set docs line length limit

crates/identity/README.md
Update docs so it matches the structure of other readme's . Also added explanation for functions inside the identity crate
=> docs(identity): update to match other docs

crates/runtime/README.md
Added a README for the runtime, which covers the main areas and operations.
=> docs: Add runtime crate README.md

crates/store/README.md
Added a README for the store, which covers the main areas and operations.
=> docs: Add store crate README.md

crates/server/README.md
Added README.md docs for admin server which is split into three parts: admin-api, json rpc and websocket
=> docs(admin-server): admin api + websockets + json rpc

crates/context/README.md, crates/identity/README.md, crates/network/README.md, crates/runtime/README.md, crates/server/README.md, crates/store/README.md
=> chore: format docs

crates/server/src/admin/handlers/context.rs, crates/server/src/admin/service.rs
Test
POST
Auth headers: {..}
http://localhost:2428/admin-api/contexts/{context_id}/join
=> feat: expose context join in admin api

crates/server/src/admin/handlers/context.rs
Added key pair param as optional for join context API request. If key pair not provided then create random inside the API and proceed with the flow. -> the new key pair is saved in the DB and can be fetched with contextID as key. 
Right here -> 
Additional PR for updating the JSON rcp -> user calls the json rpc as usually, put the calimero sender as optional and then if not provided fetch from the DB previously stored keypair to proceed with the calls.
=> fix(admin-api): join context optional keypair

packages/calimero-sdk/build-script-admin.sh, packages/calimero-sdk/build-script.sh
Build script updated by removing parts connected with components that were removed from core repository (admin dashboard / example)
=> fix(calimero-sdk): update build script

crates/sdk/macros/src/logic/arg.rs, crates/sdk/macros/src/logic/method.rs
Calling `init` in an already-initialized app was a foot-gun, as it would discard the old state, and reinitialize.
This prevents that. And also, fixes some error spans.
=> fix(sdk-macros): prevent initialization over existing state

crates/context/src/lib.rs, crates/meroctl/src/cli/context/create.rs, crates/server/src/admin/handlers/context.rs, crates/server/src/admin/service.rs
Output example
GET {{url}}/admin-api/contexts/2GAJpURPC2cGYgSkZNjk3oLWwmca6CYyMf7j4CUcWLZA/identities
```
{
"data": {
"identities": [
"4zvwRjXUKGfvwnParsHAS3HuSVzV5cA4McphgmoCtajS"
]
}
}
```
=> feat: expose context identities

crates/meroctl/src/cli/context/create.rs, crates/meroctl/src/cli/context/mod.rs, crates/node/src/lib.rs, crates/server-primitives/src/admin.rs, crates/server/src/admin/handlers/context.rs, crates/server/src/admin/utils/context.rs
Test
`cargo run -p meroctl -- --node-name coordinator --home data context create -c <contextId> --watch <path>`
=> feat: enable defining context id in context creation cli command

crates/server/src/admin/service.rs
=> fix: list applications handler error handling

crates/context/src/lib.rs, crates/node/src/lib.rs, crates/server-primitives/src/admin.rs, crates/server/src/admin/service.rs
Add new endpoint to fetch app details
=> feat: add /applications/:app_id endpoint

node-ui/src/api/dataSource/NodeDataSource.ts, node-ui/src/hooks/useMetamask.tsx, node-ui/src/hooks/useNear.tsx
Change in admin API for login requires this change on frontend call to work.
=> feat(node-ui): update signing key param name

crates/runtime/examples/demo.rs, crates/runtime/examples/fetch.rs, crates/runtime/examples/rps.rs
From the root 
`cargo run --package calimero-runtime --example rps -- <path>`
=> fix: runtime/examples rps

contracts/package-manager/src/lib.rs, contracts/package-manager/tests/mock.rs
Fix contract build.
Test
Run in package-manager ./build.sh
=> fix: package-manager build

contracts/package-manager/tests/sandbox.rs
=> fix: package manager tests

.husky/pre-commit, crates/primitives/src/hash.rs, node-ui/.husky/pre-commit, node-ui/package.json, pnpm-lock.yaml
Execute different commands on pre-commit based on changed files.
To enable husky run `pnpm install` from the root
=> chore:  extend husky precheck

scripts/build-all-apps.sh
Add script that will be called during tests
./scripts/build-all-apps.sh
```
./../apps/kv-store/build.sh executed successfully.
./../apps/only-peers/build.sh executed successfully.
./../apps/gen-ext/build.sh executed successfully.
```
=> chore: add script to build all example apps

packages/calimero-sdk/package.json
=> feat(sdk): bump version to 34

node-ui/src/components/login/applicationLogin/AppLoginPopup.tsx, node-ui/src/components/login/applicationLogin/CreateAccessTokenStep.tsx, node-ui/src/components/login/applicationLogin/SelectContextStep.tsx, node-ui/src/constants/en.global.json
Add error message for create token.
=> fix(node-ui): popup login error message

node-ui/src/components/login/applicationLogin/AppLoginPopup.tsx
=> fix(node-ui): client login cleanup

crates/server-primitives/src/admin.rs
Fixed wallet_metadata format for starknet login
=> fix:updated WalletMetadata payload format

crates/server/src/admin/utils/jwt.rs
Fixed name of variable so that it matches the ones in frontend
=> fix:updated name of executor inside of JWT token

crates/store/src/entry.rs, crates/store/src/key.rs, crates/store/src/key/application.rs, crates/store/src/key/blobs.rs, crates/store/src/key/context.rs, crates/store/src/key/generic.rs
Leftover pieces from https://github.com/calimero-network/core/pull/630
=> chore: fix store imports

crates/primitives/src/context.rs, scripts/build-all-apps.sh, scripts/test.sh
=> chore(CI): fix CI

crates/node/src/lib.rs, crates/primitives/src/context.rs
some report permissions following #719
cc: @MatejVukosav
=> chore(iCLI): report revisions

node-ui/src/api/dataSource/NodeDataSource.ts, node-ui/src/api/nodeApi.ts, node-ui/src/components/context/ContextTable.tsx, node-ui/src/components/context/startContext/StartContextCard.tsx, node-ui/src/pages/StartContext.tsx
Enabled create context option again (navigation + page) and updated params that were changed in the api.
Fixes # -
https://github.com/user-attachments/assets/1ef48aca-a251-40b4-b7e9-0442e4cba614
=> feat(node-ui): create context option

contracts/context-config/src/mutate.rs, contracts/context-config/tests/sandbox.rs, crates/context/config/src/types.rs, crates/context/src/lib.rs, crates/primitives/src/application.rs, crates/store/blobs/src/lib.rs, crates/store/src/types/application.rs
https://github.com/calimero-network/core/pull/728#discussion_r1761233820
=> feat: config contract stores application size

Cargo.lock, crates/meroctl/Cargo.toml
Release new version of the node for deployment
=> chore: bump meroctl version

node-ui/package.json, node-ui/src/api/dataSource/NodeDataSource.ts, node-ui/src/api/nodeApi.ts, node-ui/src/auth/headers.ts, node-ui/src/components/common/Button.tsx, node-ui/src/components/common/Loading.tsx, node-ui/src/components/icp/Icp.tsx, node-ui/src/components/metamask/MetamaskWallet.tsx, node-ui/src/components/setup/SetupModal.tsx, node-ui/src/components/starknet/StarknetWallet.tsx, node-ui/src/constants/en.global.json, node-ui/src/context/WalletSelectorContext.tsx, node-ui/src/pages/setup/index.tsx, node-ui/src/utils/authHeaders.ts, node-ui/src/utils/storage.ts, pnpm-lock.yaml
Remove functions and components imported from calimero-sdk in admin dashboard
Fixes # [PR 1](https://github.com/calimero-network/core/issues/577)
https://github.com/user-attachments/assets/2be24e8f-124c-439e-a53b-223f139d3bbc
=> feat(node-ui): remove sdk imports form admin dashboard

node-ui/src/components/applications/InstallApplicationCard.tsx, node-ui/src/components/context/startContext/ApplicationsPopup.tsx, node-ui/src/components/login/applicationLogin/AppLoginPopup.tsx, node-ui/src/components/login/applicationLogin/CreateAccessTokenStep.tsx, node-ui/src/components/login/applicationLogin/ListItem.tsx, node-ui/src/components/login/applicationLogin/SelectContextStep.tsx, node-ui/src/components/login/applicationLogin/SelectIdentityStep.tsx, node-ui/src/components/login/applicationLogin/StartContextPopup.tsx, node-ui/src/components/login/applicationLogin/StartContextStep.tsx, node-ui/src/constants/en.global.json, node-ui/src/utils/copyToClipboard.ts
User can create or select existing context in the process of login (selecting identity + creating access token):
Fixes # [I574](https://github.com/calimero-network/core/issues/574)
Aware of bad UI/UX but to keep the main goal of this task. 
Additional PR for updating and cleaning up will be created.
https://github.com/user-attachments/assets/0e32672c-d453-4775-8bcf-dd3ea9bf6390
=> feat(node-ui): create context in login process

.github/workflows/build_node_ui.yml
Verify that there have been changes pushed in node-ui folder, clone admin dashboard repository and copy all files from node-ui to admin dashboard. 
This should automate deploying github pages to latest version
=> feat(workflows): updated node-ui workflow

crates/context/src/lib.rs, crates/server-primitives/src/admin.rs, crates/server/src/admin/handlers/applications.rs, crates/server/src/admin/service.rs, node-ui/src/api/dataSource/NodeDataSource.ts, node-ui/src/api/nodeApi.ts, node-ui/src/components/applications/ApplicationRowItem.tsx, node-ui/src/components/applications/ApplicationsTable.tsx, node-ui/src/components/applications/InstalledApplicationRowItem.tsx, node-ui/src/components/common/ActionDialog.tsx, node-ui/src/constants/en.global.json, node-ui/src/pages/Applications.tsx
Added new api endpoint for app uninstall + code for ctx manager to delete it from node.
Updated applications page to display proper values (previously missing metadata)
Option to uninstall application.
Application can only be uninstalled if no context is using it.
Fixes # Issue #524 
https://github.com/user-attachments/assets/7d92c25a-341e-4e76-bcf4-d571f7c4a876
=> feat(admin-api+admin-ui): option to uninstall applications from node

.github/workflows/build_node_ui.yml
=> fix(workflow): rebase update

node-ui/build/index.html
=> feat(node-ui): update build

Cargo.lock, Cargo.toml, crates/node/src/runtime_compat.rs, crates/runtime/Cargo.toml, crates/runtime/src/logic.rs, crates/runtime/src/logic/imports.rs, crates/runtime/src/store.rs, crates/sdk/Cargo.toml, crates/sdk/src/env.rs, crates/sdk/src/sys.rs, crates/storage/Cargo.toml, crates/storage/src/tests/entities.rs
- Added `storage_remove()`, which was missing.
- Added a `generate_uuid()` host function. This is necessary because the guest does not have randomness available.
- Added a `time_now()` host function. This is necessary because the guest does not have randomness available.
=> feat: WASM extras

crates/node/src/interactive_cli.rs, crates/node/src/interactive_cli/call.rs, crates/node/src/lib.rs, crates/primitives/src/context.rs, crates/runtime/examples/demo.rs, crates/runtime/examples/fetch.rs, crates/runtime/examples/rps.rs, crates/runtime/src/logic.rs, crates/runtime/src/logic/imports.rs, crates/sdk/src/env.rs, crates/sdk/src/sys.rs
tests are passing node is building.
=> feat: exposed application context id to the sdk through runtime

crates/context/src/lib.rs, crates/store/src/handle.rs, crates/store/src/key.rs
=> feat: generalize deleting whole context scopes

.github/workflows/rust.yml
=> chore: use cache for clippy

.github/workflows/stale.yml
=> fix: change stale cron job interval

crates/merod/gen_localnet_configs.sh
=> Fix script for initialising calimero nodes

crates/node/src/interactive_cli/identity.rs, crates/node/src/interactive_cli/state.rs, crates/node/src/interactive_cli/transactions.rs, crates/primitives/src/context.rs
=> chore: improved interactive cli context iteration

.github/actions/style/action.yml, .github/workflows/rust.yml, packages/calimero-sdk/src/subscriptions/subscriptions.ts
Reverts calimero-network/core#906
=> Revert "chore(CI): maximize disk space"

crates/sdk/macros/src/logic/method.rs, crates/storage/src/address.rs
=> chore: simplified method macro logic to use Interface::root method

.github/actions/style/action.yml, Cargo.lock, apps/kv-store/src/lib.rs, contracts/proxy-lib/src/lib.rs, contracts/test-counter/src/lib.rs, crates/context/src/lib.rs, crates/network/src/discovery.rs, crates/network/src/events/rendezvous.rs, crates/node/src/catchup.rs, crates/node/src/interactive_cli.rs, crates/node/src/interactive_cli/context.rs, crates/node/src/interactive_cli/identity.rs, crates/node/src/interactive_cli/state.rs, crates/node/src/interactive_cli/store.rs, crates/sdk/src/types.rs, crates/server/src/admin/handlers/context/create_context.rs, crates/server/src/admin/service.rs, crates/storage/Cargo.toml, crates/storage/src/address.rs, crates/storage/src/env.rs, crates/storage/src/types.rs
Continuation of https://github.com/calimero-network/core/pull/910
=> chore: fix clippy errors & reenable warnings check

Cargo.lock, Cargo.toml, apps/visited/Cargo.toml, apps/visited/build.sh, apps/visited/src/lib.rs
Added a simple showcase app of set and map working together being nested. 
Wasm binary is building.
=> feat: added a simple app with nested map and set

crates/context/src/lib.rs, crates/node/src/lib.rs, crates/node/src/sync.rs, crates/node/src/sync/blobs.rs
props to @alenmestrov for observing unexpected behavior
=> fix: sync issues

Cargo.lock, crates/node/Cargo.toml, crates/node/src/interactive_cli.rs, crates/node/src/interactive_cli/applications.rs, crates/node/src/interactive_cli/call.rs, crates/node/src/interactive_cli/context.rs, crates/node/src/interactive_cli/identity.rs, crates/node/src/interactive_cli/peers.rs, crates/node/src/interactive_cli/state.rs, crates/node/src/interactive_cli/store.rs
Descriptions, delegate parsing to clap, and present standard output
=> chore: interactive cli touchups

crates/node/src/lib.rs
Reverts calimero-network/core#951
=> Revert "fix  deserialize proposal actions"

apps/blockchain/src/lib.rs, contracts/proxy-lib/src/lib.rs, contracts/proxy-lib/src/mutate.rs, contracts/proxy-lib/tests/common/proxy_lib_helper.rs, contracts/proxy-lib/tests/sandbox.rs, crates/context/config/src/lib.rs, crates/context/config/src/types.rs, crates/node/src/lib.rs, crates/sdk/Cargo.toml, crates/sdk/src/env/ext.rs
Please include a summary of the change and which issue is fixed. Please also
include relevant motivation and context. List any dependencies that are required
for this change.
Fixes # (Add Jira tickets related to this change)
instructions so we can reproduce. Please also list any relevant details for your
test configuration. Add screenshots or videos for changes in the user-interface.
works
=> Fix  proxy contract proposal

apps/blockchain/src/lib.rs
=> Fix: enable other peers to create proposal

.github/workflows/contributions.yml
Action is failing on pr review comment
=> fix: trigger contribution action only on issue comment

crates/sdk/src/env/ext.rs
Added code for all proposal action types to be submitted from dev applications
=> Feat  enable all proposal actions

Cargo.lock, crates/meroctl/Cargo.toml
Changelog
`Added --output-format json for machine-readable output (meroctl)
`
=> chore: release meroctl 0.2.0.

Cargo.lock, crates/merod/Cargo.toml
Changelog
- Add ICP support
Required by https://github.com/calimero-network/core/pull/1016
=> chore: release merod v0.2.1

crates/context/config/src/client/env/proxy/query.rs, crates/context/config/src/client/env/proxy/query/context_storage_entries.rs, crates/context/config/src/client/env/proxy/query/context_variable.rs, crates/context/config/src/client/env/proxy/types/starknet.rs, crates/context/config/src/types.rs, crates/context/src/lib.rs, crates/server/src/admin/handlers/proposals.rs, crates/server/src/admin/service.rs
Introduced endpoints for fetching context variables by key value or by limit and offset.
=> Feat add context variable fetching functionalities

contracts/icp/context-config/tests/integration.rs, contracts/icp/context-proxy/tests/integration.rs, contracts/near/context-config/src/mutate.rs, contracts/near/context-config/src/query.rs, contracts/near/context-config/tests/sandbox.rs, contracts/near/context-proxy/tests/common/config_helper.rs, crates/context/config/src/client/env/config/mutate.rs, crates/context/config/src/client/env/config/mutate/methods.rs, crates/context/config/src/client/env/config/query.rs, crates/context/config/src/client/env/config/query/fetch_nonce.rs, crates/context/config/src/client/env/config/types/starknet.rs, crates/context/config/src/icp/types.rs, crates/context/config/src/lib.rs, crates/context/src/lib.rs
Large change so separated in PR. 
Proxy tests near:
Config tests near:
=> feat: move nonce to request

contracts/icp/context-config/deploy_devnet.sh
Updated ICP deployment script to reflect newly introduced changes in code.
=> Icp deployment script optimization

node-ui/src/hooks/useIcp.tsx
Updated login process with II to bypass the Metamask and other wallets Extensions messages.
=> fix: updated II login process so that it doesnt listen to MM

.github/pull_request_template.md
Update the pull request template. It should be upheld by all who are trying to merge a PR into the master branch.
No tests needed
No documentation update needed.
=> feat: update PR template

node-ui/build/index.html, node-ui/src/components/login/applicationLogin/StartContextPopup.tsx
Fixed protocol values and labels in node-ui on context creation.
=> Fix node-ui protocol value options and build node-ui

crates/meroctl/src/cli/context/get.rs
Write out the identities one by one in each line.
There is room for improvement, adding additional data to the identities, like it's name (when that funcionality is merged in master).
Ran: 
`cargo run -p meroctl -- --node-name node_test_1 context get 8H9ksaSeuDaF1xYrmnWCshHA6BBrjA7WBbcAaYtxgQ7d identities
`
to verify output.
Output for `--output-format plaintext` went from
`Identities: GetContextIdentitiesResponse { data: ContextIdentitiesResponseData { identities: [PublicKey(Hash("FbNbZEXfVHFi9mAktiZKUFyQ9Wm542cYL6Jz2VBvYH39"))] } }`
to:
`FbNbZEXfVHFi9mAktiZKUFyQ9Wm542cYL6Jz2VBvYH39`
`--output-format json` left unchanged
None needed
=> refactor: update context identity output

CHANGELOG.md, Cargo.lock, crates/meroctl/Cargo.toml, crates/merod/Cargo.toml
Releasing version 0.4.0 of Calimero
Changelog:
- Added Stellar integration
- Added support for aliases which can replace hash based IDs
- Minor fixes on admin dashboard
- Optimized e2e tests
- Optimized release process
- Unified release artifacts into single Github Release
- Extracted install scripts to `install-sh` repository
=> feat: bumped version of merod and meroctl, updated changelog

CHANGELOG.md
Released 18th Feb, and link to the diffs.
=> chore: touchup changelog

crates/meroctl/src/cli/context/invite.rs, crates/meroctl/src/cli/context/join.rs
Some output was wrong or badly formatted.
Tried one "round" of inviting and joining a context.
No need
=> fix(meroctl): Small output fixes

node-ui/build/index.html, node-ui/src/components/context/startContext/StartContextCard.tsx, node-ui/src/components/login/applicationLogin/StartContextPopup.tsx
Option to create EVM context from node-ui 
TBD
=> feat(node-ui): create evm context

.github/workflows/e2e-tests.yml, e2e-tests/src/driver.rs, e2e-tests/src/main.rs
Instead of hard-coding expectations from the report, we introduce a subcommand for e2e tests that aid the combination of multiple reports into one.
=> chore(CI): impl dynamic report combination

.github/workflows/e2e-tests.yml, Cargo.lock, crates/context/config/src/client/env/proxy/query/context_storage_entries.rs, e2e-tests/Cargo.toml, e2e-tests/config/scenarios/kv-store/test.json, e2e-tests/src/driver.rs, e2e-tests/src/main.rs, e2e-tests/src/meroctl.rs, e2e-tests/src/steps/application_install.rs, e2e-tests/src/steps/get_proposals.rs
- Introduced functionality to run multiple protocols at the same time
- Optimized application install
- Fixed context_storage_entries endpoint
- Brought back kv-store scenario
- Resolved [PR](https://github.com/calimero-network/core/pull/1142) comments 
Run e2e tests locally with one of the enabled protocols flag
N/A
=> Fix  General e2e improvements

.github/pull_request_template.md, CONTRIBUTING.md, STYLE.md
Add a rust style section.
N/A
N/A
=> docs(contributing): add rust style guide

scripts/zksync/deploy-devnet.sh, scripts/zksync/nuke-devnet.sh
Add deploy and nuke devnet for zksync
Added deploy and nuke devnet scripts for zksync to prepare for the next steps of the integration. The contracts repo uses normal anvil, instead probably best to move that one to zk-anvil as well.
```
chefsale@chefsale-X670-GAMING-X-AX-V2:~/workspace/core$ ./scripts/zksync/deploy-devnet.sh 
✅ [SUCCESS] Hash: 0xe62220febbfe7a51a27e88d3abe1c32403c95811c8b08b7d0237282170fd7bdb
Initiator: 0xffffffffffffffffffffffffffffffffffffffff
Payer: 0xffffffffffffffffffffffffffffffffffffffff
Gas Limit: 300_000 | Used: 300_000 | Refunded: 0
Paid: 0.0000075000 ETH (300000 gas * 0.02500000 gwei)
Refunded: 0.0000000000 ETH
^C
chefsale@chefsale-X670-GAMING-X-AX-V2:~/workspace/core$ ./scripts/zksync/nuke-devnet.sh 
ZKsync Era processes stopped …
```
=> feat: add deploy and nuke devnet for zksync

.github/workflows/pr-description-check.yml
The PR description validation error message was quite confusing
| Before | After |
| - | - |
| ![CleanShot 2025-04-19 at 04 56 18@2x](https://github.com/user-attachments/assets/2d3f52b5-19d7-4cab-af7f-6447a2219a65) | ![CleanShot 2025-04-19 at 04 52 35@2x](https://github.com/user-attachments/assets/fd687bb0-a8fc-4bdc-88cd-0a9b590fb3c5) |
Screenshot is attached
--
=> chore(ci): patch pr description validation error message

crates/meroctl/src/cli.rs
Updating instructions for meroctl / merod as some of the things are outdated.
Testing will be done with terminal outputs to show what was not working and whats the new solution.
N/A
=> fix(cli): meroctl help update

.github/workflows/release.yml
Changed conditions for release of docker images
N/A
N/A
=> fix: dont release docker on every PR

crates/context/Cargo.toml, crates/context/primitives/Cargo.toml, crates/context/primitives/src/client.rs, crates/context/src/handlers/update_application.rs, crates/node/primitives/Cargo.toml, crates/server/Cargo.toml, crates/server/src/admin/handlers/alias/create_alias.rs, crates/server/src/admin/handlers/alias/delete_alias.rs, crates/server/src/admin/handlers/alias/lookup_alias.rs, crates/server/src/admin/handlers/applications/get_application.rs, crates/server/src/admin/handlers/applications/install_application.rs, crates/server/src/admin/handlers/applications/install_dev_application.rs, crates/server/src/admin/handlers/applications/list_applications.rs, crates/server/src/admin/handlers/applications/uninstall_application.rs, crates/server/src/admin/handlers/context/create_context.rs, crates/server/src/admin/handlers/context/delete_context.rs, crates/server/src/admin/handlers/context/get_context.rs, crates/server/src/admin/handlers/context/get_context_identities.rs, crates/server/src/admin/handlers/context/get_contexts.rs, crates/server/src/admin/handlers/context/invite_to_context.rs, crates/server/src/admin/handlers/context/join_context.rs, crates/server/src/admin/handlers/context/update_context_application.rs, crates/server/src/admin/handlers/identity/generate_context_identity.rs, crates/server/src/admin/handlers/peers.rs, crates/server/src/admin/handlers/proposals.rs, crates/server/src/lib.rs
Implemented ContextClient and NodeClient in server crate
N/A
N/A
=> feat: Actor model server methods implementation

Cargo.lock, crates/context/primitives/src/client.rs, crates/node/Cargo.toml, crates/node/src/handlers/network_event.rs, crates/node/src/interactive_cli.rs, crates/node/src/interactive_cli/applications.rs, crates/node/src/interactive_cli/call.rs, crates/node/src/interactive_cli/context.rs, crates/node/src/interactive_cli/identity.rs, crates/node/src/interactive_cli/peers.rs, crates/node/src/interactive_cli/state.rs, crates/node/src/interactive_cli/store.rs, crates/node/src/lib.rs, crates/server/src/admin/handlers/context/get_context_identities.rs
Reworked node crate to use Context and Node Clients instead of ctx_manager
N/A
N/A
=> feat:  merod methods adjustment to context and node client

Cargo.lock, crates/context/src/handlers/execute.rs, crates/merod/Cargo.toml, crates/merod/src/main.rs, crates/primitives/Cargo.toml, crates/store/Cargo.toml, crates/store/tests/rocksdb.rs
Some build warnings from master, some from the actor refactor
It compiles
None needed
=> chore: post-actor refactor cleanup

.github/workflows/pr-description-check.yml
1. CI should fail on bad description (missing from #1222)
2. Support quotes and backticks, mitigating code injection
- Case Study (ref):
3. add debug lines, just in case
It works
WYSIWYG
=> chore(ci): patches to description check

crates/context/primitives/src/client/external/proxy.rs, crates/meroctl/src/cli/context/alias.rs, crates/meroctl/src/cli/context/identity.rs, crates/meroctl/src/cli/context/identity/alias.rs, crates/node/src/interactive_cli/context.rs, crates/node/src/interactive_cli/context/identity.rs, crates/server/primitives/src/admin.rs, crates/server/src/admin/handlers/proposals.rs
Missing pieces from #1171 & patches to #1227.
Stuff I observed while working on #1263.
CI & Local testing
`clap` to the rescue
=> chore: missing pieces in meroctl & merod

e2e-tests/config/protocols/ethereum/demo-blockchain-integrations.json
Fixed issue with concurrent ETH requests in e2e tests
Run e2e tests locally for ethereum
N/A
=> fix: resolved issue with ethereum mutate request in e2e tests

crates/auth/config/config.toml, crates/auth/src/api/handlers/client_keys.rs, crates/auth/src/auth/middleware.rs, crates/auth/src/config.rs, crates/auth/src/main.rs, crates/auth/src/providers/impls/mod.rs, crates/auth/src/providers/impls/near_wallet.rs, crates/auth/src/providers/impls/user_password.rs
Introduced option for users to login with username and password.
https://github.com/user-attachments/assets/b938fe39-4e17-426a-8e42-5715e8f619cb
TBD
=> feat(Auth): Username and password authentication provider

.github/workflows/comment.yml, .github/workflows/e2e-tests-ignored.yml
addendum to https://github.com/calimero-network/core/pull/1354, workflow_run forces us to merge first before testing :-)
--
--
=> chore: test for non-PR comment fix

Dockerfile.auth, docker-compose.prod.yml
Fixed naming of auth crate and set user to root for auth
Run docker-compose -f docker-compose.prod.yml up
N/a
=> fix: auth docker setup

crates/merod/src/cli/init.rs
`merod init --force` did not previously remove the old database, it just overwrote the config file, leading to nonsense data in the newly initialized node
--
--
=> fix: forced init should remove the old database

crates/server/build.rs
Small oversight in https://github.com/calimero-network/core/pull/1378, after fixing the issue, I now made it conditional on the presence of `CALIMERO_WEBUI_FETCH_TOKEN`, which was wrong.
Delete the cache in `target/debug/cache/webui`, and build `calimero-server`, it should work with and without a token. Works for me.
--
=> fix(build): unconditionally accept octet-stream from GH

crates/auth/src/providers/impls/near_wallet.rs, crates/context/config/src/client/protocol/near.rs, crates/merod/src/cli.rs
Adding FastNEAR as default endpoint but needs API KEY.
^^^
It compiles.
N/A for now.
=> feat: added NEAR_API_KEY env var to the client

crates/version/Cargo.toml
=> chore: release 0.8.0-rc.6

Cargo.lock, crates/version/Cargo.toml
Include latest version of admin dashboard v.1.4.1
skip
skip
=> chore: release 0.8.0-rc.7

Cargo.lock, Dockerfile, Dockerfile.auth, crates/version/Cargo.toml
Please include a short description of the change and which issue is fixed.
Please also include relevant motivation and context. List any dependencies that
are required for this change.
instructions so we can reproduce. Is it possible to add a test case to our
end-to-end tests with changes from this PR? Add screenshots or videos for
changes in the user-interface.
=> fix: include tools into docker images

crates/server/src/admin/handlers/blob.rs
close #1421 
support server can success delete blob
1、 run server
2、test delete blob
=> feat: support delete blob

.github/workflows/publish-crates.yml, Cargo.toml
feat: remove the timeout from publish and bump crates
^^^
no timeout once landed
N/A
=> feat: remove the timeout from publish and bump crates

.github/workflows/ci-checks.yml, .github/workflows/release.yml
slow ci
slow ci
should still run
N/A
=> chore(ci): bump the release machine

crates/auth/src/api/handlers/auth.rs, crates/auth/src/auth/token/jwt.rs, docker-compose.prod.yml
Changed to use host header for checking the request 
instructions so we can reproduce. Is it possible to add a test case to our
end-to-end tests with changes from this PR? Add screenshots or videos for
changes in the user-interface.
=> fix(Auth): Improve auth headers checking during JWT token verification

crates/server/src/lib.rs
Fixed issue with loading static files
Start node and navigate to admin-dashboard
=> fix(Server): dont log static files

Cargo.lock, crates/version/Cargo.toml
=> chore: release 0.8.0-rc.11

Cargo.lock, tools/calimero-abi/Cargo.toml, tools/cargo-mero/Cargo.toml
=> fix: compilation errors: add serde features for semver and reqwest

crates/client/src/lib.rs, crates/storage/src/lib.rs, crates/storage/src/tests/common.rs, crates/wasm-abi/src/validate.rs, crates/wasm-abi/tests/abi_conformance.rs, crates/wasm-abi/tests/invariants.rs, crates/wasm-abi/tests/normalize.rs
=> fix: warnings in the wasm-abi and storage

Cargo.lock, crates/version/Cargo.toml
Please include a short description of the change and which issue is fixed.
Please also include relevant motivation and context. List any dependencies that
are required for this change.
instructions so we can reproduce. Is it possible to add a test case to our
end-to-end tests with changes from this PR? Add screenshots or videos for
changes in the user-interface.
=> chore: release 0.8.0-rc.16

Cargo.lock, crates/version/Cargo.toml
Please include a short description of the change and which issue is fixed.
Please also include relevant motivation and context. List any dependencies that
are required for this change.
instructions so we can reproduce. Is it possible to add a test case to our
end-to-end tests with changes from this PR? Add screenshots or videos for
changes in the user-interface.
=> chore: release 0.8.0-rc.17

CHANGELOG.md, Cargo.lock, crates/version/Cargo.toml
Incremental release
na
pushing the versioned docs PR later today
=> chore: release 0.8.0
