- packages/calimero-sdk/package.json
- packages/calimero-sdk/src/api/dataSource/NodeApiDataSource.ts
- packages/calimero-sdk/src/api/httpClient.ts
- packages/calimero-sdk/src/api/nodeApi.ts
- packages/calimero-sdk/src/wallets/MetamaskLogin/MetamaskRootKey.tsx
- packages/calimero-sdk/src/wallets/NearLogin/NearRootKey.tsx
Overlooked in process of updating auth headers -> auth headers added to the root key sdk.
> fix(calimero-sdk): update auth logic for root key

- crates/meroctl/src/cli/config.rs
- `None` no user specification
- `Some({ mdns: true, no_mdns: false })` when `--mdns`
- `Some({ mdns: true, no_mdns: true })` when `--no-mdns`
Specifying both `--mdns` and `--no-mdns` is forbidden
> chore: fix `mdns` discrimination logic

- packages/calimero-sdk/package.json
- packages/calimero-sdk/src/wallets/MetamaskLogin/LoginWithMetamask.tsx
- packages/calimero-sdk/src/wallets/MetamaskLogin/MetamaskRootKey.tsx
- packages/calimero-sdk/src/wallets/NearLogin/NearLogin.tsx
- packages/calimero-sdk/src/wallets/NearLogin/NearRootKey.tsx
As root keys and logins were a bit confusing; new descriptions are added to sdk wallet selectors
Fixes # [GI423](https://github.com/calimero-network/core/issues/423)
> feat(calimero-sdk): wallet selector improvement

- crates/meroctl/gen_localnet_configs.sh
- crates/meroctl/src/defaults.rs
This solves #450 and #451 
The build script is updated so it builds the new `meroctl` binary, and uses new initialization methods. 
Also default directory for `meroctl` changed from `/data` to `/.calimero`
running `./crates/meroctl/gen_localnet_configs.sh 3` from the root of this repository creates three nodes (`node1`, `node2`, `node3`) in the `~./calimero` directory
> chore: update localnet build script

- crates/context/README.md
Documents the `context` crate
For now, we're leaving out encryption, in-state representation, multiple-identities on a single node, etc.
We'll revisit when we have implementations of these pieces.
> docs(context): add context crate readme

- crates/context/src/lib.rs
- crates/meroctl/src/cli/context/create.rs
- crates/meroctl/src/cli/context/list.rs
- crates/server-primitives/src/admin.rs
- crates/server/src/admin/handlers/context.rs
- crates/server/src/admin/service.rs
Moved shared structs from `meroctl` and admin handler methods to `server-primitives`.
Node no longer subscribes to `application_id` when installing the app in `dev-mode`.
> Moved structs to server-primitives

- crates/server/src/admin/handlers/context.rs
Error response:
400 Bad Request
{
"error": "Invalid context id"
}
> fix: join context api error type

- crates/context/src/lib.rs
- crates/network/src/events/mdns.rs
- crates/node/src/catchup.rs
- crates/node/src/lib.rs
- crates/node/src/types.rs
- crates/server-primitives/src/admin.rs
- crates/server/src/admin/service.rs
Goal is that the node does not have to know where the application binary is hosted (testnet / mainnet NEAR view calls). Node should only get the path and download the release from the path + compare downloaded hash with hash passed in the request. 
With this update we don't need function to fetch application release to get that metadata because its passed in the API request. 
Connected with [this](https://github.com/calimero-network/admin-dashboard/pull/43) PR. 
Fixes # [Issue](https://github.com/calimero-network/core/issues/477)
> feat(admin-api): update install application logic

- Cargo.lock
Upgrading from `rustc 1.79.0` -> `rustc 1.80.0` leads to this issue:
```console
error[E0282]: type annotations needed for `Box<_>`
--> /Users/miraclx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.34/src/format_description/parse/mod.rs:83:9
|
83 |     let items = format_items
|         ^^^^^
...
86 |     Ok(items.into())
|              ---- type must be known at this point
|
help: consider giving `items` an explicit type, where the placeholders `_` are specified
|
83 |     let items: Box<_> = format_items
|              ++++++++
```
Fixed in https://github.com/time-rs/time/pull/671.
Quick `cargo update -p time` resolves this.
> chore(deps): fix broken `time` in CI

- packages/calimero-sdk/package.json
- packages/calimero-sdk/src/subscriptions/subscriptions.ts
- packages/calimero-sdk/src/subscriptions/ws.ts
Test:
I have an [app](https://github.com/calimero-network/core-app-template/pull/6) that receives new value after mutation with button. 
https://github.com/user-attachments/assets/64f9f9df-7b3e-4a57-b876-81b19fcf2574
> fix: json rpc subscriptions

- crates/server/src/admin/handlers/context.rs
- crates/server/src/admin/utils.rs
- crates/server/src/admin/utils/identity.rs
Private and public keys were required but not provided.
- private and public keys are now optional parameter
- generate new keypair if not provided
> fix: Request failed with status: 415 Unsupported Media Type

- crates/node/src/lib.rs
- crates/server/src/admin.rs
- crates/server/src/admin/handlers/context.rs
- crates/server/src/admin/utils.rs
- crates/server/src/admin/utils/context.rs
- crates/server/src/admin/utils/identity.rs
Unify context creation code in `node` and `server`.
- remove contextId from parameters during context creation with CLI
- indicate that private_key is optional in CLI
Test
`cargo run -p  meroctl -- --node-name node1 --home data context create --application-id 5Fi5jFcwoNVkV9Ngzc2Gs18GKKFtaAbsg72bdxi4FAhV`
`context create 5Fi5jFcwoNVkV9Ngzc2Gs18GKKFtaAbsg72bdxi4FAhV
`
> refactor: unify context creation

- crates/node/src/lib.rs
- crates/server/src/admin/handlers/context.rs
- crates/server/src/admin/utils/context.rs
Share the code for context joining between `node` and `server`
- remove `public_key` from server parameters as we can construct it from `private_key`
> refactor: unify context join

- packages/calimero-sdk/package.json
- packages/calimero-sdk/src/api/nodeApi.ts
- packages/calimero-sdk/src/auth/headers.ts
- packages/calimero-sdk/src/wallets/NearLogin/NearLogin.tsx
- packages/calimero-sdk/src/wallets/NearLogin/NearRootKey.tsx
As server does not need to know NEAR network (mainnet / testnet) reverted changes to previous implementation
> fix(calimero-sdk): revert near wallet type

- packages/calimero-sdk/package.json
- packages/calimero-sdk/src/types/rpc.ts
Updated types as json rpc now requires executor public key.
Type of number as public key bytes need to be transformed from uint8Array because its throwing 
error from server:` "invalid type: map, expected an array of length 32"`
> feat(sdk): update json rpc request type

- crates/store/src/db/memory.rs
- crates/store/src/db/rocksdb.rs
RocksDB's raw iter requires seeking [to the start](https://github.com/calimero-network/core/blob/a35dd9a1ec16ebf83c2b3e15cf9960f4ec923dd4/crates/store/src/db/rocksdb.rs#L77), at which point we have the first item. Since this isn't a product of calling `DBIter::seek`, we haven't gotten the item, so this is an accommodation for reading the value in the first call of `next`.
This makes us behaviorally equivalent to `InMemoryIter`.
> fix(rocksdb): pre-sought iter accomodations

- crates/store/tests/rocksdb.rs
`Database` requires the provision of consistency guarantees for all implementations even in the face of concurrent writes, which lets us have state mutations without `&mut`.
the `Layer` traits `ReadLayer` and `WriteLayer` are not defined in that way, so `Temporal` store & `ReadOnly` don't
This can be resolved by switching out `Transaction` to `InMemoryIter` which already defines those guarantees.
This will be resolved in the future PR.
> chore(store): ignore temporal mutual exclusion issues temporally

- crates/context/src/lib.rs
- crates/meroctl/src/cli/app/install.rs
- crates/meroctl/src/cli/context/create.rs
- crates/node/src/catchup.rs
- crates/node/src/lib.rs
- crates/node/src/types.rs
- crates/primitives/src/application.rs
- crates/server-primitives/src/admin.rs
- crates/server/src/admin/handlers/applications.rs
- crates/server/src/admin/handlers/context.rs
- crates/server/src/admin/service.rs
- crates/store/src/types/application.rs
The issue with previous approach is that it is missing a link between application metadata that is saved in the package-manager smart contract and this is needed for properly displaying and identifying applications from the admin dashboard.
> fix(admin-api): link installed application with package manager

- packages/calimero-sdk/package.json
- packages/calimero-sdk/src/api/dataSource/NodeApiDataSource.ts
- packages/calimero-sdk/src/api/httpClient.ts
- packages/calimero-sdk/src/api/nodeApi.ts
- packages/calimero-sdk/src/storage/storage.ts
- packages/calimero-sdk/src/wallets/MetamaskLogin/LoginWithMetamask.tsx
- packages/calimero-sdk/src/wallets/NearLogin/NearLogin.tsx
JSON rpc now requires executor public key (for query and mutate requests) which we get by calling admin api endpoint /contexts/id/identities.
This api is fetched and its data stored to local storage under "context-identity". The fetch occurs after user logged in successfully. 
From the applications side the user now when building FE for the app only needs to fetch and parse context identity from local storage and use it as a param in JSON rpc requests under "executorPublicKey".
> feat(sdk): add context identity logic

- Cargo.lock
- crates/context/Cargo.toml
- crates/context/src/lib.rs
- crates/meroctl/src/cli/context/create.rs
- crates/node-primitives/src/lib.rs
- crates/node/src/lib.rs
- crates/server-primitives/src/admin.rs
- crates/server/src/admin/handlers/context.rs
- crates/server/src/admin/utils/context.rs
- crates/server/src/jsonrpc.rs
Context creation should initialize the context with the provided parameters
Concern: `meroctl context create --context-id` will also initialize the context with parameters, making histories in dev mode irreconcilable
Fix: make `context join` have `--watch` as well.
> feat: take initialization parameters at context creation

- contracts/package-manager/src/lib.rs
Radioactive, stay away..
This is here temporarily, while the ABI/other node behaviors change, certain apps will be inevitably fall out of compatibility.
We need to garbage collect these from time to time.
So there are no guarantees for stability atm.
We guard against unauthorized erasure, only the account it's deployed on can call the method.
Example transaction from an unauthorized user:
https://testnet.nearblocks.io/txns/E93p86PiZSisVPJgUJs9in7cCMTbzsSSyNq5KJPoN4hk
> feat(registry): add erase command

- crates/node/src/lib.rs
Metadata field was mandatory and it only worked if something is sent at the end.
I have set now that version is required and metadata are optional.  Extending params to be passed with arg name requires too much work atm.
> fix: app install metadata

- crates/context/src/lib.rs
- crates/node-primitives/src/lib.rs
- crates/node/src/catchup.rs
- crates/node/src/lib.rs
- crates/server/src/jsonrpc.rs
The current (master) context initialization model would require context creation on the coordinator first, before it can be used elsewhere.
This is due to `init` being scheduled and awaiting confirmation from a coordinator that doesn't even know to subscribe to the context.
This is resolved by side stepping the coordinator flow entirely for context initialization.
> fix: side step coordinator for context initialization

- packages/calimero-sdk/package.json
- packages/calimero-sdk/src/setup/SetupModal.tsx
To make context id switching dynamic and not hardcoded in envs when deploying application; input field for context id is added on the setup page. ContextId Is needed because in the process of login the api for fetching context identities is called. 
Fixes # -
https://github.com/user-attachments/assets/4cc12385-69e3-4bdf-8cfa-94a7c8120d03
> feat(sdk): add setup context id input

- crates/sdk/macros/src/logic/method.rs
Building only-peers was producing error 
```
--> apps/only-peers/src/lib.rs:44:1
|
44  | #[app::logic]
| ^^^^^^^^^^^^^
| |
| expected `&Result<_, _>`, found `Result<Vec<u8>, Vec<u8>>`
| arguments to this function are incorrect
|
= note: expected reference `&Result<_, _>`
found enum `Result<Vec<u8>, Vec<u8>>`
```
> fix: invalid argument in app logic

- crates/sdk/tests/macros.rs
Ignore all macro tests as they are currently failing. We will go back to that with https://github.com/calimero-network/core/issues/245
> refactor: ignore macro tests

- crates/server/Cargo.toml
- crates/server/src/admin/service.rs
- crates/server/src/lib.rs
- crates/server/src/middleware.rs
- crates/server/src/middleware/host.rs
Added new middleware which is "host" that checks if the api is called from the same location as server.
For web application this will make only admin dashboard work as it will be running on the same location as server (e.g. localhost:2428).
Used referer header as it gets added by browsers.
Connected with [this](https://github.com/calimero-network/core/issues/572) issue.
#Tests:
> feat(admin-api): enable admin api for admin dashboard host only

- crates/primitives/src/hash.rs
- crates/primitives/src/identity.rs
calimero-primitives `cargo build` was failing with   `^^^^^ use of undeclared crate or module `borsh``
> fix: calimero primitives build

- node-ui/src/api/dataSource/NodeDataSource.ts
- node-ui/src/api/nodeApi.ts
- node-ui/src/auth/storage.ts
- node-ui/src/components/login/applicationLogin/AppLoginPopup.tsx
- node-ui/src/components/login/applicationLogin/ContextListItem.tsx
- node-ui/src/components/login/applicationLogin/CreateAccessTokenStep.tsx
- node-ui/src/components/login/applicationLogin/ListItem.tsx
- node-ui/src/components/login/applicationLogin/SelectContextStep.tsx
- node-ui/src/components/login/applicationLogin/SelectIdentityStep.tsx
- node-ui/src/components/protectedRoutes/ProtectedRoute.tsx
- node-ui/src/constants/en.global.json
- node-ui/src/context/AppLoginContext.tsx
- node-ui/src/main.tsx
This login process will be used by frontends for installed applications. (e.g. only peers, app template).
Missing parts in this is handler from the SDK that will be used by apps itself.
When user is redirected to admin dashboard (with application id entered in the frontend app) he is shown login popup -> select context -> select identity -> create jwt -> redirected to frontend (callbackURL)
Last part in video missing as I'm waiting for JWT pr to be merged.
Fixes # [Issue](https://github.com/calimero-network/core/issues/571)
https://github.com/user-attachments/assets/6241bf6c-734e-487f-b667-e6a776e62dc9
> feat(node-ui): new application login popup

- crates/server/src/admin/utils/jwt.rs
- crates/server/src/lib.rs
- crates/server/src/middleware.rs
- crates/server/src/middleware/jwt.rs
Removed previous auth header for jsonrpc and added new one which takes jwt token from headers, decoded it using jwt secret and passed or denies the request.
Fixes #
> feat(jsonrpc): add jwt auth middleware

- crates/meroctl/src/cli/app/install.rs
- crates/meroctl/src/cli/app/list.rs
- crates/meroctl/src/cli/context.rs
- crates/meroctl/src/cli/context/create.rs
- crates/meroctl/src/cli/context/delete.rs
- crates/meroctl/src/cli/context/get.rs
- crates/meroctl/src/cli/context/list.rs
- crates/meroctl/src/common.rs
- crates/server/src/admin/service.rs
All out apis regarding context can now be used through the CLI. 
Fixes #592 
Ran these commands on my non coordinator node (node 2 in this case)
The context with the id `EDwcrKJ9uhywwjFYssNmLzzJaj3AfDty6SxG9Pi2Juab` was already created
`cargo run -p meroctl -- --node-name node2 context get --method context  --context-id EDwcrKJ9uhywwjFYssNmLzzJaj3AfDty6SxG9Pi2Juab 
`
`cargo run -p meroctl -- --node-name node2 context get --method client-keys  --context-id EDwcrKJ9uhywwjFYssNmLzzJaj3AfDty6SxG9Pi2Juab 
`
`cargo run -p meroctl -- --node-name node2 context get --method storage  --context-id EDwcrKJ9uhywwjFYssNmLzzJaj3AfDty6SxG9Pi2Juab 
`
`cargo run -p meroctl -- --node-name node2 context get --method identities  --context-id EDwcrKJ9uhywwjFYssNmLzzJaj3AfDty6SxG9Pi2Juab 
`
All produce correct …
> Added all methods regarding context

- Cargo.lock
- crates/meroctl/Cargo.toml
- crates/meroctl/src/cli/app.rs
- crates/meroctl/src/cli/app/get.rs
- crates/meroctl/src/cli/app/install.rs
- crates/meroctl/src/cli/context/create.rs
- crates/server-primitives/src/admin.rs
- crates/server/src/admin/service.rs
All apis regarding applications are now available through the cli, including installing an app with an URL
Solves #593 and #585 
`cargo run -p meroctl -- --node-name node2 app get --method details --app-id <app-id>
`
`cargo run -p meroctl -- --node-name node2 app install --url <url> --metadata <metadata>`
> Added all application functions to the cli

- crates/meroctl/src/cli/app/get.rs
The function `get_response()` in the app/get.rs file was missing the request_type.
> Minor patch for CLI

- crates/storage/src/entities.rs
- crates/storage/src/lib.rs
- crates/storage/src/tests/entities.rs
This is the second of a series of PRs bringing in the storage and synchronisation functionality. This one creates the storage entities required, and builds on the previous https://github.com/calimero-network/core/pull/700
- Added foundation of storage entities
  - Added a new `entities` module to the `storage` crate.
  - Added the basic foundational shape for `Element`, `Data`, and `Metadata`.
- This is mergeable but not complete. Further functionality will come in further PRs.
- This is based on a stable origin point. All added tests pass.
- The previous PR https://github.com/calimero-network/core/pull/700 needs to merge to master first, then the target of this PR can change.
> feat: Added foundation of storage entities

- crates/storage/src/interface.rs
- crates/storage/src/lib.rs
- crates/storage/src/tests/interface.rs
This is the third of a series of PRs bringing in the storage and synchronisation functionality. This one creates the storage interface required, and builds on the previous https://github.com/calimero-network/core/pull/701
- Added foundation of storage interface
  - Added a new `interface` module to the `storage` crate.
  - Added an `Interface` struct as a basic foundation for the shape of this functionality.
- This is mergeable but not complete. Further functionality will come in further PRs.
- This is based on a stable origin point. All added tests pass.
- The previous PR https://github.com/calimero-network/core/pull/701 needs to merge to master first, then the target of this PR can change.
> Feat: Storage interface

- crates/storage/src/entities.rs
- crates/storage/src/interface.rs
- crates/storage/src/tests/entities.rs
- crates/storage/src/tests/interface.rs
This is the sixth of a series of PRs bringing in the storage and synchronisation functionality. This one brings save and load functionality, and builds on the previous https://github.com/calimero-network/core/pull/704
- Implemented save and update logic in storage system
  - Added `created_at` and `updated_at` timestamps to `Metadata`.
      - Added an `is_dirty` flag to `Element`.
      - Updated `Element::new()` to set the timestamps and dirty flag.
      - Added an `update_data()` method to `Element`, to allow the stored data to be updated. This sets the dirty flag and updates the `updated_at` timestamp.
      - Added `created_at()` and `updated_at()` methods to `Element`, to obtain the timestamps from its metadata.
      - Added an `is_dirty()` method to `Element`, to get the dirty …
> Implemented save and update logic in storage system

- crates/context/src/lib.rs
- crates/store/blobs/Cargo.toml
- crates/store/blobs/examples/blobstore.rs
- crates/store/blobs/src/lib.rs
- crates/store/src/types/blobs.rs
Since the eventual functionality is to request the blob from peers, and the only way to determine it's legit is to collect the entire thing, we have to limit the receipt to prevent malicious peers from infinitely flooding with useless data.
This is the foundation of further pieces that'll make it in as part of the general effort behind the other context config PRs.
We'll store the blob ID as well as the size of the blob on the contract, so you start with knowledge of how large the stream received from your peers is supposed to be.
For now, we don't immediately delete the received chunks, we'll eventually introduce garbage collection to a number of things, including this.
> feat(blobstore): abort stream once a specified content size is hit

- Cargo.lock
- crates/context/Cargo.toml
- crates/context/config/Cargo.toml
- crates/context/config/src/client.rs
- crates/context/config/src/client/relayer.rs
- crates/context/config/src/lib.rs
- crates/context/config/src/repr.rs
- crates/context/config/src/types.rs
- crates/context/src/lib.rs
- crates/meroctl/src/cli/context/create.rs
- crates/node-primitives/src/lib.rs
- crates/server/src/admin/utils/auth.rs
Adds a foundational library for interacting with the context config contract à la #680.
This also introduces a relayer implementation. NEAR to come.
> feat(context-config): add base client w/ relayer impl

- Cargo.lock
- crates/context/Cargo.toml
- crates/context/config/src/client.rs
- crates/context/src/lib.rs
- crates/meroctl/src/cli/context/join.rs
- crates/node/src/catchup.rs
- crates/node/src/lib.rs
- crates/primitives/src/context.rs
- crates/server-primitives/src/admin.rs
- crates/server/src/admin/handlers/context.rs
- crates/server/src/admin/service.rs
- crates/store/src/db.rs
- crates/store/src/key.rs
- crates/store/src/key/context.rs
- crates/store/src/types.rs
- crates/store/src/types/context.rs
- Context creation registers it on the config contract
- Context joining now requires invitation
Admin Dashboard can now feature context invitation & joining
Updated catchup logic coming in another PR
Leave context behaviour under the current model is yet to be determined, for now, it stays at local deletion
```console
context ls
│ Context ID                                   | Application ID                               | Last Transaction
application ls
│ Application ID                               | Blob ID                                      | Version      | Source
│ 3dTQEovDrrTVqFoTXRDef5M2VQM51osB66XRdTnT7uRb | Hht83G2PVqB9kZHEwBosdtDPQnmovmBXBfVnnbXJznHA |              | file:///Users/miraclx/git/calimero-is-near/cali2.0-experimental/apps/kv-store/res/kv_store.wasm
```
```console …
```
> feat(context): revise context membership process

- Cargo.lock
- crates/node/Cargo.toml
- crates/node/src/catchup.rs
- crates/node/src/types.rs
Application versions are now managed by the context contract introduced in #680. We no longer need the catchup negotiation.
We do, however, need to conditionally fetch the application from other peers if we don't have it, which is tracked in https://github.com/calimero-network/core/issues/705.
> feat(catchup): remove application negotiation from catchup

- crates/context/src/lib.rs
Deletion of a context should remove not just the `ContextMeta` entry, but also `ContextState`, `ContextIdentity`, `ContextTransaction` & `ContextConfig`
> chore(context): deletion should remove all artifacts

- crates/context/src/lib.rs
interactive CLI shouldn't require an absolute path input
> fix: canonicalize application path on installation

- crates/context/src/lib.rs
Storing the identity should be the last piece of the puzzle in case of an error. Otherwise, it results in a bricked state.
> fix: failed join shouldn't brick joining

- Cargo.toml
We're a bit bloated on the release build:
```text
Build Time: 3m43s
Binary Size: 51563272 (52M)
cmd:`strip`: 39163592 (39M)
cmd:`tgz`: 18664114 (19M)
```
\+ `strip = "symbols"`
```text
Build Time: 3m34s
Binary Size: 39163848 (39M)
cmd:`strip`: 39163832 (39M)
cmd:`tgz`: 16148833 (16M)
```
\+ `lto = "fat"`
```text
Build Time: 7m5s
Binary Size: 32735160 (33M)
cmd:`strip`: 32735144 (33M)
cmd:`tgz`: 15115760 (15M)
```
\+ `codegen-units = 1`
```text
Build Time: 6m59s
Binary Size: 30748200 (31M)
cmd:`strip`: 30748184 (31M)
cmd:`tgz`: 14381231 (14M)
```
\+ `opt-level = "z"`
```text
Build Time: 4m29s
Binary Size: 19113560 (19M)
cmd:`strip`: 19113544 (19M)
cmd:`tgz`: 10360714 (10M)
```
\+ `panic = "abort"`
```text
Build Time: 4m8s
Binary Size: 16643768 (17M)
cmd:`strip`: 16643752 (17M)
cmd:`tgz`: …
```
> feat: release profile optimizations

- Cargo.lock
- crates/context/config/src/client/config.rs
- crates/context/src/lib.rs
- crates/meroctl/Cargo.toml
- crates/meroctl/src/cli.rs
- crates/meroctl/src/cli/relay.rs
Add `meroctl relay` command. This will use the NEAR credentials defined in `config.toml`.
> feat: context config relayer impl

- .github/workflows/calimero_node_linux.yml
- .github/workflows/calimero_node_macos.yml
`actions/cache@v4` performs counter-intuitively from what the code expects, as will pull old versions of the artifact if it deems it sufficient, which will use old versions of the application instead of the one we just built.
`actions/upload-artifact@v4` and `actions/download-artifact@v4` more appropriately matches what the intent is.
https://github.com/calimero-network/core/releases/tag/v0.2.0-beta.2 for example, contains the binary for `v0.2.0-beta.1` and https://github.com/calimero-network/core/releases/tag/v0.2.0-beta.1, contains the binary for `v0.1.0`
> fix(release): use upload-artifact instead of cache for artifact smuggling

- contracts/context-config/src/guard.rs
- contracts/context-config/src/mutate.rs
- contracts/context-config/tests/sandbox.rs
Add erase method to context config contract
Needed to nuke the contract after #738.
I've since nuked the contract and redeployed the new version.
> feat(config-contract): add erase method

- Cargo.lock
- crates/meroctl/Cargo.toml
Following #748, it was identified that all the current releases v0.1, v0.2-beta-* don't contain binaries that are the versions they claim to
I've gone ahead to delete those tags and their releases to give us a fresh slate
> chore(release): bump meroctl to v0.1.0

- crates/meroctl/src/defaults.rs
Use the deployed instance of the relayer as the default
> feat: revise default relayer url

- node-ui/src/components/context/ContextTable.tsx
- node-ui/src/pages/Contexts.tsx
- node-ui/src/pages/JoinContext.tsx
Removed join context button from context page and added redirect when user navigates to that page with url
> feat(node-ui): remove join context

- crates/meroctl/src/cli/init.rs
- crates/network/src/config.rs
- crates/network/src/discovery.rs
- crates/network/src/discovery/state.rs
- crates/network/src/lib.rs
- crates/network/src/tests/discovery/state.rs
>At the moment we request our relay reservation from all relay peers. Implement selection of relay peers to avoid network congestion.
>One approach could be to select the first N peers as nominated peers. After our reservation has expired, we could nominate a new peer and request a reservation.
> Improve relay registration

- Cargo.lock
- Cargo.toml
- crates/meroctl/Cargo.toml
- crates/meroctl/src/cli/context.rs
- crates/meroctl/src/cli/context/watch.rs
- crates/server-primitives/src/ws.rs
Described in #541, you can "listen" to incoming data regarding a context 
Fixes #541
`cargo run -p meroctl -- --node-name <node-name> context watch --context-id <context-id>` starts the process
> Implement CLI commands for interaction with WebSocket endpoint

- packages/calimero-sdk/package.json
- packages/calimero-sdk/src/rpc/jsonrpc.ts
Update all return types for type safe + returning "null" instead of "undefined".
Fixes # [Issue](https://github.com/calimero-network/core/issues/456)
Tested Only-Peers + Template App
> feat(sdk): update return types for json rpc

- packages/calimero-sdk/package.json
- packages/calimero-sdk/src/login/refreshToken.ts
- packages/calimero-sdk/src/rpc/jsonrpc.ts
- packages/calimero-sdk/src/types/rpc.ts
With this PR error handling (parsing) is updated. Now all returned errors are handled with proper error messages and responses.
The Error structure is from proposed solution defined in Issue for this task.
Requires also bump version of sdk for App Template and Only Peers application
Fixes #114 
Alerts for RPC errors. The user who builds application decides how each error will be displayed.
> feat(sdk): update json rpc error handling

- crates/server/src/admin/service.rs
> feat(node): output logs for admin api and admin ui

- Cargo.lock
- crates/meroctl/Cargo.toml
Notable changes:
- https://github.com/calimero-network/core/pull/721
- https://github.com/calimero-network/core/pull/760
- https://github.com/calimero-network/core/pull/752
- https://github.com/calimero-network/core/pull/778
> chore(release): bump meroctl to v0.1.1

- crates/meroctl/src/cli/app/get.rs
- crates/meroctl/src/cli/app/install.rs
- crates/meroctl/src/cli/app/list.rs
- crates/meroctl/src/cli/context/create.rs
- crates/meroctl/src/cli/context/delete.rs
- crates/meroctl/src/cli/context/get.rs
- crates/meroctl/src/cli/context/join.rs
- crates/meroctl/src/cli/context/list.rs
- crates/meroctl/src/cli/context/watch.rs
- crates/meroctl/src/common.rs
```
╭─    ~/workspace/core/apps   implement-watch-flag ▓▒░                                          ░▒▓ ✔  17:40:00 ─╮
╰─ cargo run -p meroctl -- --node-name coordinator app --help                                                           ─╯
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.87s
Running `/Users/chefsale/workspace/core/target/debug/meroctl --node-name coordinator app --help`
Usage: meroctl --node-name <NAME> app <COMMAND>
Commands:
get
install
list
help     Print this message or the help of the given subcommand(s)
Options:
-h, --help  Print help
```
> chore: simplified the use of multiaddrs and config inside the cli

- crates/storage/src/address.rs
- crates/storage/src/entities.rs
- crates/storage/src/interface.rs
- crates/storage/src/tests/common.rs
- crates/storage/src/tests/entities.rs
- crates/storage/src/tests/interface.rs
- Removed the temporary `Data` struct and implemented a proper `Data` trait in its place. This temporarily has an associated type called `Child`, to specify the (one-dimensional) type of children.
- Added `element()`and `element_mut()` methods to obtain the `Element` that the `Data` type owns.
- Added `id()` and `path()` methods for convenience to pass through from `Data` to `Element`.
- Added documentation to explain the design choices behind the implemented structure.
- Removed the `Element.data` property and matching `data()` method, as `Element` will no longer own or have any reference to `Data`; `Data` needs to own `Element` for the chosen design pattern.
- Updated the `Element.update_data()` method to no longer accept `Data`, as it does not have access to it. Renamed it to simply …
> feat: Finalised Data trait and associated design

- Cargo.lock
- Cargo.toml
- crates/storage-macros/Cargo.toml
- crates/storage-macros/src/lib.rs
- crates/storage-macros/tests/atomic_unit.rs
- crates/storage-macros/tests/compile_fail/atomic_unit.rs
- crates/storage-macros/tests/compile_fail/atomic_unit.stderr
- crates/storage/Cargo.toml
- crates/storage/src/entities.rs
- crates/storage/src/tests/common.rs
- crates/storage/src/tests/entities.rs
- crates/storage/src/tests/interface.rs
- crates/test-utils/Cargo.toml
- crates/test-utils/src/lib.rs
- crates/test-utils/src/storage.rs
Added `AtomicUnit` macro and trait
- Added a new `AtomicUnit` marker trait.
- Added a new `storage-macros` crate, to contain the macros needed for presenting the high-level developer interface.
- Added an `AtomicUnit` proc macro to automatically derive `AtomicUnit` and `Data` traits for a struct.
Added `test-utils` crate
- Created a new `test-utils` crate, to contain common functions and data structures for the purpose of testing.
- Moved common functionality that has a wider scope from `storage::common` to `tests-utils::storage`.
> feat: Added AtomicUnit macro and trait

- Cargo.lock
- Cargo.toml
- crates/storage-macros/src/lib.rs
- crates/storage-macros/tests/collection.rs
- crates/storage-macros/tests/compile_fail/collection.rs
- crates/storage/Cargo.toml
- crates/storage/src/entities.rs
- crates/storage/src/interface.rs
- crates/storage/src/tests/common.rs
- crates/storage/src/tests/entities.rs
- crates/storage/src/tests/interface.rs
Added `ChildInfo`
- Added a `ChildInfo` struct to encapsulate basic information about the children of an `Element`, which needs to be stored with the `Element`. At present this is the child `Element`'s ID and Merkle hash.
- Renamed the `child_ids()` method and `#[child_ids]` field attribute to `child_info`.
- Amended the `AtomicUnit` implementation of `Interface.calculate_full_merkle_hash()` to only load from the database if recursing, and to otherwise use the now-available stored hash.
Added `Data.collections()`
- Added a `collections()` method to the `Data` trait, to return a list of all collections with `ChildInfo` for all their children.
Added `Interface.compare_trees()`
- Added an `Action` enum to represent the various actions that can be required as a result of tree comparison, in …
> feat: Interface sync

- crates/meroctl/src/cli.rs
- crates/meroctl/src/cli/app/get.rs
- crates/meroctl/src/cli/app/install.rs
- crates/meroctl/src/cli/app/list.rs
- crates/meroctl/src/cli/context/create.rs
- crates/meroctl/src/cli/context/delete.rs
- crates/meroctl/src/cli/context/get.rs
- crates/meroctl/src/cli/context/join.rs
- crates/meroctl/src/cli/context/list.rs
- crates/meroctl/src/cli/context/watch.rs
- crates/meroctl/src/common.rs
The `load_config` refactor in #793 lost some information, notably no longer loading the config from the node's home dir, the effect of which only works when the executor's CWD is inside the node's home dir
> fix: load config should factor in node's home dir

- Cargo.lock
- crates/sdk/src/tests/mocks.rs
- crates/storage-macros/Cargo.toml
- crates/storage-macros/src/lib.rs
- crates/storage-macros/tests/atomic_unit.rs
- crates/storage-macros/tests/collection.rs
- crates/storage-macros/tests/compile_fail/collection.rs
- crates/storage-macros/tests/compile_fail/collection.stderr
- crates/storage/Cargo.toml
- crates/storage/src/address.rs
- crates/storage/src/entities.rs
- crates/storage/src/index.rs
- crates/storage/src/interface.rs
- crates/storage/src/lib.rs
- crates/storage/src/tests/common.rs
- crates/storage/src/tests/entities.rs
- crates/storage/src/tests/index.rs
- crates/storage/src/tests/interface.rs
- crates/storage/src/tests/mocks.rs
Added Merkle tree indexing
- Added `index` module to the `storage` crate, to take care of all index management. For now this is registration of the IDs and hashes of nodes in the tree. For any nodes that have children, their child collections are stored in the index data - this means it no longer has to be stored in the `Data` side, reducing the amount of serialised data in the `Action` payloads, and also opening this up for various performance optimisations that can take place in the `Index` without affecting the data side.
- Added an `Index` struct acting as an interface to the indexing, along with an `EntityIndex` struct for representing the data that gets stored. This is currently the ID, parent ID, child information (the IDs and hashes of all children, by collection), plus the hash …
> wip: Added indexing

- Cargo.lock
- crates/sdk/Cargo.toml
- crates/sdk/src/env.rs
- crates/sdk/src/lib.rs
- crates/sdk/src/tests/mocks.rs
- crates/storage-macros/Cargo.toml
- crates/storage-macros/src/lib.rs
- crates/storage-macros/tests/atomic_unit.rs
- crates/storage-macros/tests/compile_fail/collection.rs
- crates/storage-macros/tests/compile_fail/collection.stderr
- crates/storage/Cargo.toml
- crates/storage/src/address.rs
- crates/storage/src/entities.rs
- crates/storage/src/interface.rs
- crates/storage/src/tests/entities.rs
- crates/storage/src/tests/interface.rs
- Changed the `storage` crate to be accessible through the SDK for direct use by guest runtimes.
- Removed the `store` parameter from `Interface::new()`, as it will now use the central store provided to the guest and available through `env` functions.
- Removed conversion to/from `StorageKey` for `Id`, as this is no longer accessible due to the move to the SDK.
- Added mock storage to use during non-WASM testing, where the guest env's storage is not available.
- Added non-WASM calls into the mocked storage from `env`.
- Made `Interface` fully static; `Interface` no longer needs to be instantiated, and so use of `self` has been removed, along with the `new()` constructor.
- Updated storage to use WASM-compatible functions for time and UUID.
> feat: Presented storage through SDK

- crates/storage-macros/src/lib.rs
- crates/storage-macros/tests/atomic_unit.rs
- crates/storage-macros/tests/collection.rs
- crates/storage-macros/tests/compile_fail/collection.rs
- crates/storage-macros/tests/compile_fail/collection.stderr
- crates/storage/src/entities.rs
- crates/storage/src/index.rs
- crates/storage/src/interface.rs
- crates/storage/src/tests/common.rs
- crates/storage/src/tests/index.rs
- crates/storage/src/tests/interface.rs
Added type ID to entities
- Added a `type_id()` method to the `Data` trait, to provide a unique type ID per implemented `Data` type, formalising the approach to type identification.
- Added a `type_id` parameter to `Index::add_child_to()` and `Index::root()`.
Added ancestor hashes to `Action`
- Added ancestor information to `Action::Add`, `Delete`, and `Update`. This allows the ancestor hashes to be checked after applying an action, to see if further syncing is needed.
- Added an `ancestors` field to `ComparisonData`. This will be useful for checking the higher tree levels in some cases.
- Added `get_ancestors_of()` and `get_type_id()` to `Index`. The type ID is now formalised as a `u8`.
- Changed the `Action` `id` field to be a `u8`, to match `type_id`.
- Made the Action variants into …
> feat: Add ancestor hashes and type IDs

- Cargo.lock
- crates/runtime/Cargo.toml
- crates/runtime/src/logic.rs
- crates/runtime/src/logic/imports.rs
- crates/sdk/Cargo.toml
- crates/sdk/src/env.rs
- crates/sdk/src/sys.rs
1. remove `VMLogic::generate_uuid` - [ref](https://github.com/calimero-network/core/pull/799#discussion_r1800159587)
2. remove `uuid` dep from runtime & SDK - [ref](https://github.com/calimero-network/core/pull/799#discussion_r1800313072)
3. generalize `sys::generate_uuid` to `sys::random_bytes` - [ref](https://github.com/calimero-network/core/pull/799#discussion_r1800168580)
4. remove mocks for SDK functionality - ref [1](https://github.com/calimero-network/core/pull/799#discussion_r1800172131) & [2](https://github.com/calimero-network/core/pull/799#discussion_r1800172227)
- as mentioned in https://github.com/calimero-network/core/pull/781#discussion_r1801073836, this will be accommodated inside the storage crate
5. clean up `uuid` in root manifest - …
> fix: incorporate review feedback from #799

- Cargo.lock
- apps/kv-store/Cargo.toml
- apps/kv-store/src/collections.rs
- apps/kv-store/src/lib.rs
- crates/runtime/examples/demo.rs
- crates/sdk/macros/src/logic/method.rs
- crates/sdk/src/lib.rs
- crates/sdk/src/types.rs
- crates/storage-macros/Cargo.toml
- crates/storage-macros/src/lib.rs
- crates/storage-macros/tests/atomic_unit.rs
- crates/storage-macros/tests/collection.rs
- crates/storage/Cargo.toml
- crates/storage/src/entities.rs
- crates/storage/src/lib.rs
- crates/storage/src/types.rs
Updates the kv-store app to use the CRDT storage subsystem
Introduces a generic `Map` to simplify storage operations.
For now, `apply_action`, `compare_trees` and `generate_comparison_data` have not been introduced.
```console
$ ./apps/kv-store/build.sh
$ cargo run -p calimero-runtime --example demo --features host-traces -- apps/kv-store/res/kv_store.wasm
```
> feat: update kv store to use new CRDT store

- crates/context/src/lib.rs
- crates/node/src/lib.rs
- crates/node/src/runtime_compat.rs
- crates/primitives/src/events.rs
- crates/runtime/examples/demo.rs
- crates/runtime/src/logic.rs
- crates/runtime/src/logic/imports.rs
- crates/sdk/macros/src/logic/method.rs
- crates/sdk/src/env.rs
- crates/sdk/src/sys.rs
- crates/storage/src/env.rs
- crates/storage/src/interface.rs
- crates/store/src/layer/temporal.rs
- crates/store/src/tx.rs
Following a mutation, regardless of source, client or external peer, once the root hash of the state is updated, we need to pass that information to the node, which will aid later catchups
> feat: commit to new root hash following state mutations

- crates/context/src/lib.rs
- crates/node-primitives/src/lib.rs
- crates/node/src/interactive_cli/call.rs
- crates/node/src/lib.rs
- crates/server/src/jsonrpc.rs
- crates/server/src/jsonrpc/mutate.rs
- crates/server/src/jsonrpc/query.rs
Mutable & Query client execution requests now functionally do the same thing, to avoid breaking client apps (frontends), I'm retaining the `mutate` and `query` JSONRPC methods to be reconciled in a later PR
And due to optimistic execution, we no longer need `Finality` directives
cc: @fbozic & @petarjuki7, to keep you in the loop just in case
> feat: update node execution flow

- crates/node/src/runtime_compat.rs
- crates/store/src/tx.rs
`Vec`s relocate on capacity exhaustion, which invalidated the `Slice` ref, corrupting store data
> fix: runtime compat reference

- crates/context/src/lib.rs
- crates/node-primitives/src/lib.rs
- crates/node/src/interactive_cli/context.rs
- crates/server/src/admin/handlers/context/create_context.rs
`context create` may fail, especially during initialization, we shouldn't assume success when it does.
This patch ensures to only return the context id and public key of the user if creation succeeds.
And to rollback store mutations when we encounter a failure.
> fix: handle fallible context creation

- .github/workflows/stale.yml
Run every day at 2PM to check if issues or PRs are stale. First, add a label, and then after 7 days of inactivity close the issue or PR.
> chore: add stale workflow

- crates/network/src/events/gossipsub.rs
- crates/network/src/types.rs
- crates/node/src/lib.rs
- crates/primitives/src/events.rs
- crates/server/src/ws.rs
- packages/calimero-sdk/package.json
- packages/calimero-sdk/src/subscriptions/subscriptions.ts
- packages/calimero-sdk/src/subscriptions/ws.ts
`PeerId`s are a networking concept and give clients subscribed to a context no useful information.
Doc patch: https://github.com/calimero-network/calimero-network.github.io/pull/44
> chore: remove client notification of peer connection events

- crates/storage/src/address.rs
- crates/storage/src/entities.rs
- crates/storage/src/interface.rs
- crates/storage/src/store.rs
- crates/storage/src/tests/address.rs
- crates/storage/src/tests/common.rs
- crates/storage/src/tests/entities.rs
- crates/storage/src/tests/index.rs
- crates/storage/src/tests/interface.rs
> feat: increase the id bytes size and use context_id as root

- contracts/context-config/src/guard.rs
- contracts/context-config/src/lib.rs
- contracts/context-config/src/mutate.rs
- contracts/context-config/src/query.rs
- contracts/context-config/src/sys.rs
- contracts/context-config/tests/sandbox.rs
- crates/context/config/src/client.rs
- crates/context/config/src/types.rs
Introduce revisions to `Guard` that let's us more efficiently determine when to update  `application` and `members` on the node
> feat(context-config): impl guard revision, restructure modules

- node-ui/build/index.html
- node-ui/src/api/httpClient.ts
- node-ui/src/pages/setup/index.tsx
- node-ui/src/utils/storage.ts
Axios interceptor for all calls that checks if user is authorized (if no returns 401). If status is 401 it redirects user to setup page to setup again node url + login.
This can be recreated by init + setup node + run admin dashboard login. Then delete node data and recreate the steps.
The page will have in local storage items that tell the page thats its authorized but requests are not authorized as storage client key does not match the server one.
https://github.com/user-attachments/assets/f3a2aac6-6df3-4db2-8630-1729fadca1d8
> fix(node-ui): expired client key

- packages/calimero-sdk/package.json
- packages/calimero-sdk/src/types/rpc.ts
Expose `execute` method in new version.
> fix: expose execute in json rpc

- crates/node/src/lib.rs
Tested
actions [Transfer { receiver_id: "vuki.testnet", amount: 1 }]
> fix  deserialize proposal actions

- contracts/context-config/tests/sandbox.rs
Fixed issue that occured during tests in PR reviews. 
Correctly casted proposal id to [u8; 32] instead of u8.
> fix: correct casting of returned proposal ID

- crates/context/src/lib.rs
- crates/meroctl/src/cli/context/create.rs
- crates/server-primitives/src/admin.rs
- crates/server/src/admin/handlers/context/update_context_application.rs
Fix for https://github.com/calimero-network/core/issues/916
> fix: update app id in contract

- crates/node/src/lib.rs
- crates/runtime/examples/demo.rs
- crates/runtime/examples/fetch.rs
- crates/runtime/examples/rps.rs
- crates/runtime/src/logic.rs
#630 unintentionally swapped the values for `max_storage_pages` and `max_stack_size`.
Losing semantic information was a bad idea, and constructor functions for structs with all fields public are non-beneficial. Functions with many arguments, also a bad idea.
This seemingly subtle change led to a stack overflow on an intel machine, but not on M1 Pro for some reason, worth investigating later. As it's part of why it wasn't caught earlier.
> fix: stack size VM limits

- Cargo.lock
- contracts/context-config/Cargo.toml
- contracts/context-config/src/mutate.rs
- contracts/context-config/src/query.rs
- contracts/context-config/src/sys.rs
- contracts/context-config/tests/sandbox.rs
- contracts/proxy-lib/Cargo.toml
- contracts/proxy-lib/build-test-deps.sh
- contracts/proxy-lib/build.sh
- contracts/proxy-lib/src/lib.rs
- contracts/proxy-lib/src/mutate.rs
- contracts/proxy-lib/tests/common/config_helper.rs
- contracts/proxy-lib/tests/common/proxy_lib_helper.rs
- contracts/proxy-lib/tests/sandbox.rs
- crates/context/config/src/client/protocol/near.rs
- crates/context/config/src/lib.rs
- Now we are deriving subaccount from Context contract account and because of that we don't need to deposit anything in mutate method when calling Context contract
- Gas needed for deploying the contract is now determined by the size of Proxy contract, Proxy contract init arguments and minimum required funds for generating and seeding accounts instead of being static
- Unused gas is returned to Context contract account
- Optimized tests in Context config to reflect new process
- Using `#[callback_result]` for callback functions
- Fixed minor issues with code such us double json encoding, duplicates in tests, taking references, async functions declarations
> Context and Proxy Contracts Improvements

- .github/workflows/rust.yml
- Cargo.lock
- crates/node/Cargo.toml
- crates/node/src/lib.rs
Failed transactions should not;
1. Apply their changes to storage
2. Broadcast a state delta
3. Have any effect on external systems (blockchain)
> fix: prevent external mutation on execution failure

- crates/node/src/sync.rs
- crates/node/src/sync/blobs.rs
- crates/node/src/sync/key.rs
- crates/node/src/sync/state.rs
When on the receiving end of a state sync request, and we don't have the application, upgrade the sync channel to a blob share and reverse the roles. After receiving the application from the requester, go back to processing the state sync request.
This preserves the same guards employed for the traditional blob share, size, and integrity checks.
> chore: facilitate blob share during state sync if necessary

- contracts/context-config/tests/sandbox.rs
cross contract calls settled across blocks won't have been resolved by the time `transact()` returns
https://github.com/near/near-workspaces-rs/pull/379
> fix(CI): advance after transactions are fully finalized

- crates/context/config/src/client/protocol/near.rs
`TimeoutError` on `TxStatusError` is [effectively a dud](https://github.com/near/nearcore/blob/29f388f058a6fc908902b79018844c79eb95baa6/chain/rosetta-rpc/src/errors.rs#L52-L54), and from semantic analysis, it's never actually constructed by the node.
We should, instead.. match for the RPC timeout represented as the `408 Request Timeout` status code.
I've retained the check for `TxStatusError::TimeoutError` to be more exhaustive anyway.
> fix(near): handle request timeout

- contracts/context-config/src/sys.rs
- contracts/proxy-lib/src/lib.rs
- contracts/proxy-lib/src/mutate.rs
for correctness, when erasing context config, the associated proxy contracts are dangling and should be nuked
ideally, we protect against trivially calling `erase` on the context config, since it's a single source of failure
> feat: nuke proxy when erasing context config

- crates/context/config/src/client.rs
- crates/context/config/src/client/env.rs
- crates/context/config/src/client/env/config/mutate.rs
- crates/context/config/src/client/env/config/query.rs
- crates/context/config/src/client/env/proxy/mutate.rs
- crates/context/config/src/client/env/proxy/query.rs
- crates/context/config/src/client/protocol/near.rs
- crates/context/config/src/client/protocol/starknet.rs
- crates/context/config/src/client/relayer.rs
- crates/context/config/src/client/transport.rs
- crates/context/config/src/client/utils.rs
- crates/merod/src/cli/relay.rs
The goal is to further generalize the external client to support recursive nesting of structures like:
```rust
type All = Either<Relayer, Both<Near, Both<Starknet, Both<InternetComputer, Both<Ethereum, Solana>>>>>
```
or even
```rust
type NearAndStarknet =
Both<Near, Starknet>;
type EthereumAndSolana =
Both<Ethereum, Solana>;
type PolkadotAndInternetComputer =
Both<Polkadot, InternetComputer>;
type NearAndStarknetOrEthereumAndSolana =
Either<NearAndStarknet, EthereumAndSolana>;
type NearAndStarknetOrEthereumAndSolanaAndPolkadotAndInternetComputer =
Both<NearAndStarknetOrEthereumAndSolana, PolkadotAndInternetComputer>;
type RelayerOrNearAndStarknetOrEthereumAndSolanaAndPolkadotAndInternetComputer =
Either<Relayer, NearAndStarknetOrEthereumAndSolanaAndPolkadotAndInternetComputer>;
```
Which …
> feat: iterate on transport generalization for recursive declaration

- CHANGELOG.md
- Cargo.lock
- crates/merod/Cargo.toml
> chore: release v0.2.0

- scripts/install.sh
Added in parallel to the documentation update https://github.com/calimero-network/calimero-network.github.io/pull/62/files.
Actually the install script just updates the `.bashrc`. This PR adds more frequent shells and a final message for clarification.
> fix: shell compatibility in install script

- contracts/icp/context-proxy/src/mutate.rs
- contracts/near/context-proxy/src/mutate.rs
Fixed case in which users could delete other users proposals for NEAR and ICP
> fix: disabled case in which users could delete other users proposals

- contracts/icp/context-config/src/mutate.rs
- contracts/icp/context-config/tests/integration.rs
- contracts/icp/context-proxy/src/query.rs
- contracts/icp/context-proxy/tests/integration.rs
- contracts/near/context-config/src/mutate.rs
- contracts/near/context-config/tests/sandbox.rs
- crates/context/config/src/icp.rs
- crates/context/config/src/icp/types.rs
Timestamp removed from contracts as they now use nonce
> fix: remove timestamp from contracts

- crates/merod/src/cli/init.rs
Set default values for ICP as local network and self signer. This is because we decided not to go with the relayer solution for now
> feat(node): set ICP init config

- Cargo.lock
- contracts/near/context-config/Cargo.toml
- contracts/near/context-config/build.sh
- contracts/near/context-config/src/lib.rs
- contracts/near/context-config/src/mutate.rs
- contracts/near/context-config/src/sys.rs
- contracts/near/context-config/src/sys/migrations.rs
- contracts/near/context-config/src/sys/migrations/01_guard_revisions.rs
- contracts/near/context-config/src/sys/migrations/02_nonces.rs
- contracts/near/context-config/tests/migrations.rs
- contracts/near/context-config/tests/sandbox.rs
- crates/context/config/src/lib.rs
Add migrations for moving to nonces from timestamps in the near contract.
Defines an organized structure for managing migrations.
Pull the wasm blob of `calimero-context-config.testnet` at block `185_028_495`.
```console
near contract download-wasm calimero-context-config.testnet to-folder . network-config testnet at-block-height 185028495
```
Move that to `res/calimero_context_config_near_migration_member_nonces_pre.wasm`
```console
mv contract_calimero-context-config_testnet.wasm ./contracts/near/context-config/res/calimero_context_config_near_migration_member_nonces_pre.wasm
```
Then with this branch checked out, and run:
```console
./contracts/near/context-config/build.sh --migration 02_nonces
```
and copy the built wasm to `res/calimero_context_config_near_migration_member_nonces_post …
> chore(near): nonce migrations

- CHANGELOG.md
- Cargo.lock
- contracts/near/context-config/src/sys/migrations.rs
- crates/meroctl/Cargo.toml
- crates/merod/Cargo.toml
Notable changes:
- Introduced ICP integrations, achieving full feature parity with NEAR and Starknet
- Improved replay protection on external interactions, fixing spurious failures from expired requests
- Moved protocol selection to context creation, and out of the config
- Allowed the specification of all protocol's default context configuration
- Exposed, and enabled functionality for context proxy storage
- Introduced bootstrap command for quick development as a demo
> chore(merod, meroctl): release v0.3.0

- .github/workflows/rust_binaries_release.yml
Switched linux aarch64 compiler from zig to gcc while maintaining OpenSSL configuration with simplified build command
> fix: switched from zig to gcc compiler and simplified build command

- crates/context/src/lib.rs
- crates/meroctl/src/cli.rs
- crates/meroctl/src/cli/context/get.rs
- crates/meroctl/src/cli/peers.rs
- crates/server-primitives/src/admin.rs
- crates/server/src/admin/handlers.rs
- crates/server/src/admin/handlers/context/get_context_identities.rs
- crates/server/src/admin/handlers/peers.rs
- crates/server/src/admin/service.rs
Now all the functionalities from the` interactive cli` are included in the `meroctl`.
Updates from this PR include:
1.  `context get identities` (`--owned`) command - list all the identities in a context, the `--owned` command is to show only the owned identities
2. `peers` command - show the number of connected peers
`get identities` tested by creating a context, inviting one other peer and then verifying the output of the `identities` and `identities --owned` commands.
`peers` command tested by creating three nodes, and verifying that the output is `3`
No documentation update is necessary right now, although when we move form interactive cli to meroctl in our public docs it should be mentioned
> Update meroctl commands

- Cargo.lock
- Cargo.toml
- crates/context/config/Cargo.toml
- crates/context/config/src/client/env/config/mutate.rs
- crates/context/config/src/client/protocol/stellar.rs
- crates/context/config/src/stellar/stellar_types.rs
- crates/context/src/lib.rs
Fixing mutate encode function to properly pass byte arguments to context config contract.
Updating stellar types for proper casting from Stellar struct to Calimero types.
Setup node from docs and run following
```
application install file <path>
> application_id
context create <application_id> --protocol stellar
> should get error in different place and its regarding proxy which is WIP in other pr
context ls
> context should be create
```
-
> fix(core): stellar rpc mutate function + types update

- node-ui/build/index.html
- node-ui/src/api/dataSource/NodeDataSource.ts
Identity endpoint was split into two new endpoints so this change is needed so admin dashboard only displays owned context identities.
No updates
> feat(node-ui): update identity api endpoint

- .github/workflows/e2e_tests.yml
https://github.com/calimero-network/core/commit/cce742b1744e993193fcf73318cccbb75a49b0f1#r152680837 was leading to [`Error: No issue/pull request in input neither in current context.`](https://github.com/calimero-network/core/actions/runs/13369736224/job/37335851687#step:5:9) because `PR_NUMBER` was undefined.
I've also removed the `--base` branch filter, to allow for branches that don't immediately target master. As is the case with https://github.com/calimero-network/core/pull/1115.
> fix: e2e report PR number determination

- Cargo.lock
- crates/config/Cargo.toml
- crates/meroctl/Cargo.toml
- crates/meroctl/src/cli/proxy.rs
- crates/meroctl/src/cli/proxy/get.rs
- crates/meroctl/src/main.rs
- crates/server-primitives/Cargo.toml
- crates/server-primitives/src/admin.rs
- crates/server/src/admin/handlers/proposals.rs
`meroctl` has no business depending on `calimero-server`
Following this patch, it only transitively depends on it via `calimero-config`
We need to extract all the configs of `calimero-context`, `calimero-server` and `calimero-network` into light weight crates to ease that relationship.
> chore: `meroctl` should not depend on `calimero-server`

- .github/workflows/release.yml
- crates/merod/src/cli/init.rs
`signer = "self"` for stellar will almost certainly fail unless the node admin funds the testnet account.
This patch changes it to use relayer instead.
> fix: default to relayer for stellar signing

- crates/node/src/interactive_cli/context.rs
- crates/node/src/interactive_cli/peers.rs
The logic in `peers` would've always failed when no context is provided as an argument, this is now fixed.
And context invitation wasn't resolving the inviter identity under the context scope, also fixed.
> fix: peers and context invitation should resolve correctly

- .github/workflows/release.yml
`gh release view` needs a token, causes master to fail: https://github.com/calimero-network/core/actions/runs/13497216832/job/37707846721
> fix: add `GH_TOKEN` for gh command

- Dockerfile
This PR adds the ```COPY e2e-tests ./e2e-tests``` line to the Dockerfile, ensuring the e2e-tests directory (already referenced in Cargo.toml) is included in the build.
> fix: Add missing e2e-tests directory in Docker build

- contracts/icp/context-config/deploy_devnet.sh
- e2e-tests/config/scenarios/kv-store/test.json
- e2e-tests/src/driver.rs
- e2e-tests/src/meroctl.rs
- e2e-tests/src/steps.rs
- e2e-tests/src/steps/context_create_alias.rs
- e2e-tests/src/steps/jsonrpc_call.rs
Create an alias for a context on the inviter node named `my_context`, and use that alias instead of a `contextId` in subsequent jsonrpc calls.
N/A
> feat(e2e): add testing aliases to e2e tests

- e2e-tests/config/config.json
- e2e-tests/src/config.rs
- e2e-tests/src/driver.rs
- e2e-tests/src/merod.rs
We cannot account for pre-used ports in CI environments, patch e2e tests to attempt to find at least one unused port in 100 attempts, incrementing by one each time.
Should fix https://github.com/calimero-network/core/actions/runs/13939669570/job/39014375346
> fix(e2e-tests): ensure ports are available before running merod

- crates/context/src/lib.rs
- crates/merod/src/main.rs
- crates/node/src/lib.rs
- crates/node/src/sync.rs
- crates/node/src/sync/state.rs
- e2e-tests/config/config.json
- e2e-tests/config/scenarios/kv-store/test.json
- e2e-tests/src/meroctl.rs
- e2e-tests/src/steps/context_invite_join.rs
- e2e-tests/src/steps/jsonrpc_call.rs
Alen noticed some weird behaviour with encryption, turned out we were assigning a default key to peers we've never directly synced with, that was wrong.
And when the sender key is unable to decrypt a state delta, we should assume the sender key was invalid and trigger a sync (which should fetch us the latest key and the updated state).
Restored the uninitialized guard for execution.
Increased the number of nodes in e2e tests to 3.
Made the jsonrpc step retriable, in case, for example, node 1 has the state, and node2 & 3 waste their 30s sync allowance doing a pointless sync with one other. Should reduce the odds of ever failing in this process by a lot.
> fix: key sync encryption issues & make e2e tests more resilient

- crates/node/src/sync/state.rs
- e2e-tests/config/scenarios/kv-store/test.json
- e2e-tests/src/steps.rs
- e2e-tests/src/steps/wait.rs
In the best case, consensus should be reached in `ceil(log2(nodes))` sync rounds.
Assuming we sync for 5s, we can alleviate the previously enforced wait duration of 40s.
And when a node doesn't sync in that period, in the worst case we retry 20 times. Hoping in a 100s period the sync happens. 🙂
> feat(e2e): introduce an optimized wait step for the best case

- .github/workflows/pr-description-check.yml
Updated comments mentioned [here](https://github.com/calimero-network/core/pull/1160). Introduced new changes which include:
- proper required items 
- only 1 comment per PR with no commenting on each edit (previous behaviour)
- deleting comment after description edit workflow passed  
Was tested with private repository.
No documentation update needed here.
> ci(pr-description-check): only 1 comment per PR and comment cleanup

- CHANGELOG.md
- Cargo.lock
- crates/meroctl/Cargo.toml
- crates/merod/Cargo.toml
Bump meroctl and merod to version 0.5.0 
Relase logs:
- Added Ethereum integration
- Decoupled contracts from core repository
- Extended e2e tests to include proxy contract functionalities
- Added autonat protocol
N/A
Updated [here](https://github.com/calimero-network/calimero-network.github.io/commit/c470a6f97bc3fdc2d6d4c138c956cdc6fe469a79)
> feat: bump core version + release logs

- .github/workflows/pr-description-check.yml
Issue noticed in [this](https://github.com/calimero-network/core/pull/1163) PR where "` ` `" is used and it breaks the workflow
Tested in private repository [here](https://github.com/frdomovic/stellar-json-rpc/pull/21)
N/A
> ci(pr-description-check): escape special characters

- crates/meroctl/src/cli/bootstrap/start.rs
- crates/meroctl/src/cli/context/create.rs
- crates/meroctl/src/cli/context/invite.rs
- crates/meroctl/src/cli/context/join.rs
This PR fixes #1179 by adding alias support to meroctl while creating a new context, inviting new users to a context and when a new user joins.
> feat(meroctl): support creating alias on context join and invite

- apps/only-peers/src/lib.rs
- crates/storage/src/collections.rs
- crates/storage/src/collections/unordered_map.rs
- crates/storage/src/collections/unordered_set.rs
- crates/storage/src/collections/vector.rs
Patched some things that were notably absent, behaviorally inefficient or inappropriately named.
1. Should be able to create / extend;
- an `UnorderedMap` from an iterator of `(K, V)`
- an `UnorderedSet` from an iterator of `V`
- a `Vector` from an iterator of `V`
2. `UnorderedMap<K, V>: Default` doesn't need `K: Default, V: Default`
3. Checking if the collection contains some key for `Unordered{Map,Set}` shouldn't need to read `V` from storage.
Apps compile, and it works locally
The relevant bits are documented in-code, can triage to see if any external bits need to be updated but I doubt it
> chore(storage): iron out some kinks

- crates/sdk/macros/src/lib.rs
- crates/sdk/src/lib.rs
- crates/sdk/src/macros.rs
Add an `app::log!` macro which is behaviourally equivalent to the standard library's `println!`.
Tested locally, and in a secondary PR - #1199, I update the apps to use the `bail!` and `log!` macros.
After the hackathon
> feat: introduce `app::log!` convenience macro

- apps/kv-store/src/lib.rs
- apps/only-peers/src/lib.rs
- apps/visited/src/lib.rs
- crates/sdk/macros/src/lib.rs
- crates/sdk/src/lib.rs
- crates/sdk/src/macros.rs
- crates/storage/src/collections.rs
- crates/storage/src/collections/unordered_map.rs
- crates/storage/src/collections/unordered_set.rs
- crates/storage/src/collections/vector.rs
Update the apps in core to use the `app::bail!` (https://github.com/calimero-network/core/pull/1195 + https://github.com/calimero-network/core/pull/1197) and `app::log!` (https://github.com/calimero-network/core/pull/1198) macros.
It compiles
After the hackathon
> chore: update the apps in core to use the new sdk macros

- apps/kv-store/src/lib.rs
- apps/only-peers/src/lib.rs
- apps/visited/src/lib.rs
- crates/sdk/macros/src/lib.rs
- crates/sdk/src/lib.rs
- crates/sdk/src/macros.rs
- crates/sdk/src/types.rs
- crates/storage/src/collections.rs
- crates/storage/src/collections/unordered_map.rs
- crates/storage/src/collections/unordered_set.rs
- crates/storage/src/collections/vector.rs
Iterations on https://github.com/calimero-network/core/pull/1195.
The initial impl would always `Display` serializable errors, which isn't the best if you intend to parse it at the caller.
This patch uses [some](https://www.reddit.com/r/rust/comments/rnn32g/rust_already_has_specialization/) [rust-trickery](https://lukaskalbertodt.github.io/2019/12/05/generalized-autoref-based-specialization.html), different from what we [previously](https://github.com/calimero-network/core/blob/0588c5e4cc0f9db2a83d76e4ce4c4a942d813e40/crates/sdk/macros/src/logic/method.rs#L136-L148) [had](https://github.com/calimero-network/core/blob/0588c5e4cc0f9db2a83d76e4ce4c4a942d813e40/crates/sdk/src/returns.rs) for return type serialization due to needing more than 2 overrides, but it essentially exploits related …
> feat: expand possible inputs to `app::bail!`

- crates/meroctl/src/cli/context/update.rs
- crates/meroctl/src/common.rs
1. Patch `context update` bug leading to weird, non-contextual 404 response from the server.
Props to Alen for stumbling on this, and patching it.
2. Fail early on `meroctl` whenever a scope isn't provided for identity resolution.
```console
$ meroctl context update ...
```
Not needed
> fix(meroctl): alias resolution for meroctl context update

- .github/workflows/ci-checks.yml
- deny.toml
added cargo deny check licenses and sources with the deny.toml
added cargo deny check licenses and sources with the deny.toml, for now ignore all the issues, but revisit them later and clean them up one by one
also added the cleanup as subtask to https://github.com/calimero-network/core/issues/265
CI should run the check and pass.
N/A
> feat: added cargo deny check licenses and sources with the deny.toml

- crates/meroctl/src/cli/app.rs
- crates/meroctl/src/cli/app/install.rs
- crates/meroctl/src/cli/context.rs
- crates/meroctl/src/cli/context/create.rs
Changed generic "id" labels to more specific "context_id" and "application_id" in CLI output for better clarity. This improves user experience by clearly distinguishing between different types of identifiers. fix #1087
- Verified output format in all affected commands (create, list, get)
- Checked that context ID and application ID are correctly labeled
-
> fix: update output labels for application and context identifiers

- crates/meroctl/src/cli/context/watch.rs
Resolves https://github.com/calimero-network/core/issues/1072
I implemented a new meroctl command that listens for context events and triggers shell commands in response
Basic event watching (existing functionality)
`meroctl context watch`
Command execution
`meroctl context watch -x "echo 'Event received'"`
Event count limiting
`meroctl context watch -x "date" -c 3`
> feat(meroctl): Add event-triggered command execution to context watch

- crates/context/primitives/src/client.rs
Rewritten methods to ContextClient
OLD - NEW
get_contexts_ids - get_contexts
get_context_identities - context_members
has_context_identity  - has_member
update_application_id - update_application
invite_to_context - invite_member
Convenience methods:
create_context
delete_context
execute
update_application
N/A
N/A
> feat:  context client methods implementation

- .github/workflows/e2e-tests.yml
- .github/workflows/pr-description-check.yml
- .github/workflows/release.yml
in PR:
- never release binaries
- every PR gets a `:pr-N` docker tag (this one being `:pr-1294`)
- every new commit gets a `:<sha>` docker tag
on master:
- release binaries if the version changed (a version suffixed with `-pre.N` is a prerelease)
- release a `:<version>` docker tag if the version changed
- every new commit gets an `:edge` docker tag
- every new commit gets a `:<sha>` docker tag
1. The release process was unnecessarily complicated with some duplication and conditions that would never be triggered.
2. GitHub also now provides Arm64 & x86_64 runners for [macOS](https://github.com/actions/runner-images#available-images) and [ubuntu](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/), so we don't …
> chore(ci): patch release pipeline

- .github/workflows/release.yml
SHA-tagged images from PRs by default use the merge commit sha as opposed to the PRs HEAD.
my eyes
--
> fix: SHA-tagged images should be HEAD, not merge

- Cargo.lock
- crates/meroctl/Cargo.toml
- crates/meroctl/src/cli/context/list.rs
- crates/meroctl/src/cli/context/watch.rs
This patches `meroctl context watch` to;
1. support `https` node urls
2. show the execution output in a structured format, which supports `--output-format json`
3. actually pass the event emitted to the executed command, surprised this wasn't the case already
4. support executing command with flags, for example `sh -c "cat"`, `xargs -I{} echo {}`
Works in local testing
--
> fix(meroctl): `meroctl watch` should work correctly

- .github/workflows/deps/prebuilt.Dockerfile
- Cargo.lock
- Cargo.toml
- Dockerfile
- Dockerfile.auth
- crates/auth/Cargo.toml
- crates/config/Cargo.toml
- crates/meroctl/Cargo.toml
- crates/version/Cargo.toml
- docker-compose.prod.yml
1. remove unreferenced dependencies in the root manifest
2. `calimero-auth` doesn't follow the convention of `.workspace = true` (I updated the already existing dependencies, and left the ones only used by `calimero–auth`)
3. `license-file = LICENSE.md` is the default, it doesn't have to be stated
4. https://github.com/calimero-network/core/issues/1328 - GitHub's CI runner's use glibc 2.39, which we build on, and therefore link to. But `debian:bookwork-slim` had `2.36-9`, failing at runtime. Reverted to use `ubuntu:24.04` at runtime.
5. stop installing unneeded packages for the rust build in docker
6. https://github.com/calimero-network/core/issues/1335 - build arguments for the webui and auth ui should be specifiable in  docker builds
- docker build locally passes, permuting all …
> chore: docker & cargo patches for cleanup and consistency

- crates/context/primitives/src/client/sync.rs
- crates/node/primitives/src/client/application.rs
Don't try to install the application in initial context sync if the path is a local path. 
Instead, create a reference in the storage and download the application on periodical context sync.
Run 2 nodes, install the application using local path on 1st node, create a context and invite the 2nd node to it. 
Run command `application ls` on the 2nd node and notice installed flag in the output. 
After the sync run the command again and you will see that the application is installed.
N/A
> fix(Context): Don't install application from path on initial context sync

- crates/context/primitives/src/client.rs
- crates/context/src/handlers/create_context.rs
- crates/context/src/handlers/delete_context.rs
- crates/context/src/handlers/execute.rs
- crates/node/src/handlers/network_event.rs
- crates/node/src/sync.rs
- crates/node/src/sync/delta.rs
- crates/store/src/key/context.rs
1. Fix the delta ordering, we should be encoding the height in storage as big-endian instead of little-endian to take advantage of rocksdb's byte-wise lexicographical ordering
2. `context delete` should remove delta entries as well
3. When handling a broadcasted message;
1. we should appropriately store the delta artifact
2. if we sustain state variance post-delta application, the triggered sync should track time taken
4. When syncing deltas;
- once we receive a delta entry, ensure it matches the one we requested in height and author, as a sanity check
- ensure we never process out-of-sequence delta entries
- ensure to store the delta entry as a product of the operation
- log more of what happens during the sync process
- add a guard check to ensure we never return more delta entries than …
> fix: stabilize delta sync

- Dockerfile.auth
- docker-compose.prod.yml
A few things required in the services were unitentionally removed during the optimization. This PR brings them back:
`docker-compose -f docker-compose.prod.yml up`
Complete flow will be added to the next docs version
> fix: revert docker changes

- crates/auth/src/api/handlers/client_keys.rs
Commented out condition where it checked that `context_id` and `context_identity` need to be present during client key generation in auth process
Ping `/client-keys` endpoint with empty context ID and context Identity
N/A
> feat(Auth): remove context id and identity as required params

- .github/workflows/release.yml
1. Bash is weird, and regexes in strings aren't evaluated, they have to be raw.
2. `overwrite_release` should never be used. create a new release instead. PS: it didn't actually do anything before.
Tested against local bash & confirmed with this [post](https://stackoverflow.com/q/18709962/9806233).
--
> chore(CI): pre-releases should be appropriately tagged

- crates/context/primitives/src/client/sync.rs
- crates/context/primitives/src/messages.rs
- crates/context/primitives/src/messages/sync.rs
- crates/context/src/handlers.rs
- crates/context/src/handlers/sync.rs
- crates/context/src/handlers/update_application.rs
A couple of things here:
1. The `UpdateApplication` handler, after updating the application on the context config contract, was calling into `update_application` on the `ContextClient`, which in turn led to the `UpdateApplication` handler to be triggered, culminating essentially in infinite recursion.
2. The context meta cache on `ContextManager` needs to be updated when a context config sync causes us to be made aware of an application update.
Local testing
--
> fix: update application

- crates/meroctl/src/cli/call.rs
- crates/node/src/handlers/network_event.rs
- crates/node/src/interactive_cli/context.rs
- crates/server/primitives/src/jsonrpc.rs
- scripts/stage.sh
- Better output representation for `meroctl call`
- `ContextId`, `ApplicationId` and `PublicKey` with the colored representation should be consistent.
- `context delete <ctx-id>` instead of `context delete -c <ctx-id>`
--
--
> chore: qol improvements

- Cargo.lock
- crates/server/Cargo.toml
- crates/server/build.rs
This PR updates the build process to fetch a pre-built admin dashboard artifact from the GitHub release assets, rather than downloading the entire source code. This change improves build efficiency and aligns with the new semantic-release workflow.
CALIMERO_WEBUI_FETCH=1 cargo run -p merod -- --node-name node1 run
Navigate to http://localhost:2428/admin-dashboard/
N/A transparent for the user
> feat(build): fetch pre-built admin dashboard from release assets

- .github/actions/container-release/action.yml
- .github/workflows/release.yml
small oversight: `github.event.pull_request.head.repo.full_name` evaluates to `false` on `master`
we need something more general than that, I noticed the `github.event.repository` object has a `fork` field, I'm testing to see if that holds up as we expect
Observations:
1. `github.event.repository` represents the base repo, not the fork
2. `github.event.head.repo` also has a `fork` field, which is `true` when we're a fork, great
Tested pushes from a [fork](https://github.com/calimero-network/core/pull/1379), pushes to a branch (simulating master) and pushes to a [PR](https://github.com/calimero-network/core/pull/1380) within the repo.
Everything works as we expect.
--
> chore(CI): fix docker push condition

- .github/actions/container-release/action.yml
- .github/workflows/release.yml
`docker_release` is only set when the version didn't previously exist, it needs to be more general. This is on me.
--
--
> chore: decouple the responsibility of the `release` flag

- crates/storage/src/index.rs
- crates/storage/src/interface.rs
- crates/storage/src/tests/index.rs
Permit out-of-order application, that is if a.b.c is recieved before a or a.b exists locally, go ahead to create sparse entries for a and a.b, when we eventually receive the entries for a and a.b, we can fill them
```console
cargo test -p calimero-storage -- apply_action__sparse
```
--
> fix(storage): permit out-of-order delta application

- .github/workflows/ci-checks.yml
- deny.toml
Adding `LGPL-3.0-or-later` works fine, and in CI too it [appears](https://github.com/calimero-network/core/actions/runs/17117285922/job/48550750021)
--
--
> chore: restore cargo deny rules, with alternative patch

- crates/server/Cargo.toml
- crates/server/src/lib.rs
Basic logging to unblock debugging 
We are currently fully in the dark, this adds basic debug logging of the requests and responses to help triaging. First version, probably can be improved.
Run it locally and you get the nice request/response logs with debug enabled.
```
42-2025-09-08T08:31:12.871436Z DEBUG server::http: request body truncated=false body={"path":"/Users/chefsale/workspace/calimero/core/apps/kv-store/res/kv_store.wasm","metadata":[]}
43-2025-09-08T08:31:12.894820Z DEBUG server::http: response sent status=200 OK elapsed_ms=23
44:2025-09-08T08:31:12.894883Z DEBUG server::http: response body truncated=false body={"data":{"applicationId":"Es8ShuWDKipNv3ZjkxsAjCaerL9u5sqKBX7Q6cvkuGwj"}}
45-2025-09-08T08:31:12.913840Z DEBUG server::http: incoming request method=GET …
```
> feat: added basic debug request/response server logging to the crate

- Cargo.lock
- crates/server/Cargo.toml
- crates/server/src/lib.rs
responses and requests bigger than 4kb don't work due to truncation
tested locally to ensure it doesn't happen again
n/a
> fix: don't truncate and log if bigger than 4kb in server

- Cargo.lock
- crates/runtime/src/logic/host_functions/blobs.rs
- crates/server/src/lib.rs
Nothing much, updated the crate name + cleaned up some `cargo build` warnings.
na
na
na
> chore: Cleanup build warnings
